### ISSUE TITLE
Fix Validation on create new user 

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/stoplight-web#1020]
No se esta haciendo validacion de los datos al formulario de alta de usuarios

**Comment by JDelPuerto** [comment]
Si las validaciones para crear un usuario( de cualquier tipo) funcionan este issue se puede cerrar.

**Comment by aprojas** [comment]
When the Org Admin creates a new user, there should not be a field to choose the organization to which it belongs to:

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/76834de4-642d-4a43-b086-b64991997f97)

@JDelPuerto
