### ISSUE TITLE
El valor del checkbox no se limpia si cambio su condicional anterior

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1023]
## TO TEST

La pregunta de discapacidad si respondo que SI me despliega los tipos de discapacidad.
Si yo elijo una discapacidad pero después me arrepiento y cambio la pregunta anterior a NO. Funciona pero debería borrarme el dato de la discapacidad que elegí
Porque si de vuelta selecciono SI, se queda guardada la opción que yo ya había seleccionado

**error message:**

{code: "ECONOMIC_CONDITIONAL_ERROR",…}
code: "ECONOMIC_CONDITIONAL_ERROR"
message: "The following questions contain data inconsistent with the associated conditional logic: typeOfDisability"

**Comment by JDelPuerto** [comment]
Para probar este issues es recomendable descargar un reporte para asegurarse que se guardaron los valores correctamente.
