### ISSUE TITLE
Mejoras en la vista de User

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1024]
Las siguientes puntos fueron reportados desde QA

If count is more than 1, should be users found not user found. And when it's 1 it should be user found, not users found. 

El título "Nombre de usuario" cambiar a Usuario y Usuário (en español y portugues) Done
Si el nombre de un hub es muy largo y no entra en un row, entonces debería tener el mismo behavior que el email con los 3 puntos ...  

Cambiar orden a: Search by Username, name or email  

El hover text del botón de eliminar tiene un typo, debe ser Delete user  

Cambiar el texto del error al crear contraseña a: The password is too short. Use at least 5 characters.  Done
Bug: Cree un usuario con un username existente, y me recordó con el mensaje de error, pero después al hacer clic adentro y afuera otra vez, ya me apareció sin error. Igual intenté crear y me dio un error. Pero el mensaje de error del username existente debería aparecer siempre si es que no cambió, y tampoco te debería dejar hacer clic en el botón de -> No realiza correctamente la validacion del username y dejaba guardar

Para los siguientes dos issues se decidio  ubicar el select del role primero y luego  solo si seleccion el rol hub admin aparecer el select para elegir el hub correspondiente:
El campo de HUB no debe ser obligatorio. Porque si quiero crear un Ps_team, no debería tener asociado ningún Hub. Solución: poner el campo de Role arriba de Hubs. Entonces primero seleccionamos psteam o hub admin. Solo si selecciono hub admin, debe aparecer el dropdown de Hubs. Si selecciono psteam, no debería aparecer el campo de Hubs.
Bug: Al crear un nuevo usuario, si yo elijo un hub, en el campo de role ya no me debe aparecer el rol Team. Porque el Team no pertenece a ningún Hub, solo debería aparecer cuando no haya elegido ninguna opción en Hub. Ahora intenté crear y me dejó crear igual como psteam, pero claramente no aparece el Hub en la tabla.
Se podría disable el botón de Save cuando creas un nuevo usuario hasta que todos los campos se cumplan?

Bug: al crear un nuevo usuario, se debería ir al primer lugar en la fila, ahora mismo aparece en el último lugar.Backend(Ya solucionado) 

Bug: intenté crear un Hub Admin y no me permite?? Me dio dos veces un error. Done -> Culpa del nombre duplicado

Change message error, to when the user already exists, to: The username already exists  

Cuando busco por un filtro que no tiene usuarios, podríamos cambiar el texto de 0 user found a No users found ? 

Question: En el validation, así como no te deja añadir espacios o upper case aunque intentes escribir, no te podría restringir los special characters aunque intentes escribir? O sino cambiamos el mensaje de error a más específico como Solo se permiten letras (a-z), números (0-9) y separadores (.) (_). Only letters (a-z), numbers (0-9) and separators (.) (_) are allowed.  

Ningún usuario PSTEAM debería estar permitido ver el usuario root_admin, ni mucho menos poder editar o eliminar. Podríamos sacarlo luego de ahí? Porque la jerarquía mayor siempre es root_admin, entonces mejor que no le aparezca luego al ps_team.  Backend(Ya solucionado)

El usuario PSTEAM tiene permitido eliminar usuarios, en el issue habíamos escrito que solo pueda editar para dejar un usuario disabled. 

El orgadmin debería también tener el filtro de Organizaciones, ahora solo tiene el searchbox. 
19. Bug: Desde hub/hub, intenté cambiar el nombre de org/org y no me permite cambiar. Me dice que could not save user. Backend(Ya solucionado)

**Comment by loorely** [comment]
@JDelPuerto 
Se encontraron estos problemas: 
1. Cuando no se encuentra ningun dato sale mal el titulo: 

![image](https://user-images.githubusercontent.com/740232/83916947-116a1100-a744-11ea-9546-70caa6fe8f86.png)


2.
