### ISSUE TITLE
Recuperar dato de interactive_help

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-web#1044]
## Descripcion

Recuparar la información del label `interactive_help` del endpoint `/users/validate` y guardarlo en el local storage.

**Comment by JDelPuerto** [comment]
El error es el seguiente 

En el archivo Authenticator.js 135
``` TypeError: Cannot read property 'interactiveHelp' of null ```

Se produce por que el admin no tiene un objeto application.
