### ISSUE TITLE
Componente de ayuda interactiva - audio socioeconomico

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1052]
- Modificar el query graphql para obtener la información de las nuevas columnas.
- Agregar el componente de ayuda de audio por `topic`.

**Comment by JDelPuerto** [comment]
@aprojas  This feature will work perfectly only when  this  other issue [1749](https://app.zenhub.com/workspaces/stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/stoplight-server/1749) it's done. Right now if you're playing an audio and continue to the next topic the audio will continue as if nothing happened

**Comment by aprojas** [comment]
Fix the following:

1. Cuando termina el audio, se queda con la barra cargada y ya no puedo hacer clic en continuar. 
Cuando termina el audio, debe volver a su estado original de Audio Help con el ícono de play.

2. Si un audio está en reproducción, me voy una pantalla atrás o adelante, me reproduce automáticamente también el audio de ese topic. Debería parar al cambiar de una pantalla a otra.

@Guillecaba
