### ISSUE TITLE
Create & Show Error Message if data is not sent properly

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-web#107]
An error message should be shown if the survey is not synced, as well as must be handled.

**Comment by gigerbytes** [comment]
@pA1nD pls review. try disabling your internet before clicking `save & close` to show error.

@pA1nD  @stacylorraineprendeville I would need the error message to show in case the thing is not sent:

Currently it's:

`There was an error in submitting. The data is still in your browser. Please do not close the browser and contact Poverty Stoplight as soon as possible.`

**Comment by pA1nD** [comment]
### Problems:

(1)
Error is not reset when I go to this page the second time.

(2)
- I click the submit button with internet (after I clicked it w/o internet)
- The family is sent to the server and I'm redirected
- Now I go back to surveys > Continue latest draft
- I directly come to the last page and see the error message again
- I click the "Save & close" button again and I am redirected again
- there is a duplicated family now. This should not happen!

**Comment by stacylorraineprendeville** [comment]
@carloscarvallo  I need to close sprint 3 - was this reviewed - is this relevant?

**Comment by carloscarvallo** [comment]
@stacylorraineprendeville you can close it
