### ISSUE TITLE
Organization filter doesnt show surveys when chosen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1093]
In the reports section, as a Hub Admin, when I choose an organization first, then I want to select the survey for the data. However, no surveys appear in the second filter when I first choose an organization.

I think this bug appeared after the hotfix.

**Comment by JDelPuerto** [comment]
@aprojas  If you can test the survey filter in  the reports and dashboard views would be excellent to  ensure that is working properly.
