### ISSUE TITLE
Check all rollover effects in platform for the buttons

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1150]
Unify the behavior for the next components:
- Selects.
- Primary buttons.
- Secondary buttons.
- Action buttons.

**Comment by Auxi9** [comment]
El select queda como debajo del modal, esto ya se habia ajustado para otros selects.
![image.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/36113580-5165-4ac1-ba8a-b3d09930c1c1)
