### ISSUE TITLE
Add select all families component

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1168]
## Problem

Hub Admin should be able to move families. So we need a select all option (multiselect) similar to the Gmail functionality.

## Solution

This example would be for the Families list.
An initial button where if you click on the checkbox, it selects all 10 families at once.
Then a checkbox button next to each family row, where when you select one or more than one family at the same time.. 
AND then a new button that appears at the right (aligned to the other buttons) of **Move family** (with move icon).

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/461036f4-fa4d-4dd3-b482-de32e1a0ae02)

## Observations
- Available for Root Admin, Hub Admin

**Comment by hrebenarMartin** [comment]
Hello, i'd like to take up on this issue. Would that be possible ?

**Comment by JDelPuerto** [comment]
Hello! Thanks for  your offer, but unfortunately  this issue requires backend support and that it's a private project.
Also I must say we don't have any issues which could be labeled as a good first issue to start. Thanks again for your offer and good luck!

**Comment by aprojas** [comment]
Check this:

Strange background when hover on the checkbox, it is not a perfect circle and it looks pink. Should be similar to the hover of the delete icon.

@Guillecaba
