### ISSUE TITLE
Add Navigation Header to Lifemap Survey

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-web#118]
Add a navigation header that looks exactly like the one from platform.povertystoplight.org to the survey

**Comment by gigerbytes** [comment]
Implemented nav except for Language Switcher and Username tracked in the following issues:
#165
#166

**Comment by stacylorraineprendeville** [comment]
@carloscarvallo is this complete?
I cannot see it....

**Comment by carloscarvallo** [comment]
Is in the corresponding branch, I was reviewing it this morning and I have to talk with @gigerbytes more about this
