### ISSUE TITLE
Changes for Images in Family Profile

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1186]
1. Deshabilitar la flecha de la derecha si es que no hay mas imagenes hacia la derecha (que quede en gris)
2. Lo mismo el de la izquierda, que aparezca activo solo si hay imagenes hacia la izquierda
3. Que el boton de la flecha tenga el background redondo al hacer hover
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/24951442-24cc-4bb7-b885-5ffd2bc48a96)

4. Abrir la imagen en grande para poder guardar o solamente mirar, estilo redes sociales (otro sprint)?

**Comment by JDelPuerto** [comment]
El punto 4 pasa para el siguiente sprint @aprojas
