### ISSUE TITLE
Research if the pop-up can only appear once to the user

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1188]

**Comment by Guillecaba** [comment]
Se puede manejar con localstorage o con cookie si se quiere mostrar el popup una vez, almacenando el user y un boolean que indique si ya fue visitado esa vista o no, de esta manera si viene el mismo usuario en el mismo navegador, ya no se le muestra y si se logea otro usuario se agrega su username a un array.

Una forma de manejar esto es con cookies o con localstorage, en el caso de usar cookies, es una buena práctica tener un mensaje que advierta al usuario de su uso, según las leyes de EU Cookies Directive y General Data Protection Regulation.

Si usamos localstorage, se podría almacenar una clave que controle mostrar el modal una vez, la primera vez que alguien loguee en ese navegador, independientemente al usuario, si se quiere que sea por usuario, se debe guardar una clave, relacionada a algún identificador del usuario, ya sea su username por ejemplo.
Si se quiere mostrar una vez por usuario independientemente al navegador, debería haber soporte desde el backend lo cual implica agregar una nueva columna donde se almacene esa información de tal manera y esa información se podría almacenar en el storage de redux
