### ISSUE TITLE
Extra field for "Other" in Disability type

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#121]
When choosing the option "other" in disability type, the user doesn't have the option to write that other disability type. By choosing "other", an extra field (fill in the blank type) should automatically appear.

**Comment by stacylorraineprendeville** [comment]
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/221

Duplicate in the above
