### ISSUE TITLE
Endpoint to add +1 to amount of views 

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1212]
Add a column to the solutions table  to store the amount of time  it has been visited. This service should be transactional.

**Comment by diegotorrespy** [comment]
Issue moved to [FundacionParaguaya/stoplight-server #1874](https://github.com/FundacionParaguaya/stoplight-server/issues/1874) via [**ZenHub**](https://www.zenhub.com/)
