### ISSUE TITLE
Amends to design of Bank of Solutions

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1219]
2. La línea punteada podría desaparecer después de completar el título y los otros campos donde hayan líneas punteadas?
3. Poner una banderita al lado del selector de idioma
4. Al lado de la organización quitar el ícono y acercar más al switch
5. El typography del **description** podría ser poppins medium, no bold.
6. El color del título y description cambiar a el gris oscuro que usamos en la plataforma en general
7. El ícono al subir los archivos mejor si cambiamos a gris. El naranja da la sensación de que es un PPT
8. Los títulos de Recursos e Información de contacto están en fino o medium? Como son títulos capaz sería bueno ponerlos en medium
9. Cambiar el texto del botón de "Guardar" a "Publicar" , y "Publish" en inglés? Porque guardar me da la sensación de guardar para después continuar
10. Averiguar si el editor puede estar internacionalizado tambien, porque tiene tooltips y algunos textos en inglés únicamente.

**Comment by Guillecaba** [comment]
Si es ROOT ->  como hub se va Fundacion Paraguaya
Si es PSTEAM -> como hub se va Fundacion Paraguaya
si es HUB_ADMIN ->  su hub
Si es ORG_ADMIN -> se va el hub y org

**Comment by Guillecaba** [comment]
Validacion de titulo y subtitulo:
Título: 64 characters
Description: 200 characters
