### ISSUE TITLE
Logic in Forms

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#122]
We have a number of questions that can use logic to assign the answers and indeed should do so for data validity.

Example
q. People living under 18 question is redundant
In the previous section to this question, the user already has to include the number of members and its birth dates. It could automatically estimate how many members under 18 years old live in the household with that previous info?
Because it could lead to inconsistency (accidentally)

**Comment by stacylorraineprendeville** [comment]
This is a logic related issue  - Not something we can tackle easily.
Also the user has no obligation to answer the question regarding Birthdates of family members so it is a corner case
