### ISSUE TITLE
Grammar fix in education section

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#123]
In the second question:
"What is your highest educational level in your household?"
It should read:
"What is **the** highest educational level in your household?"

Exchange the "your" for "the". 

![2019-02-05 5](https://user-images.githubusercontent.com/44477708/52274465-88628000-292b-11e9-8f0a-273b029561b3.png)

**Comment by gigerbytes** [comment]
@diegotorrespy This comes from the survey definition - could we push a change to the db?

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #631](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/631) via [**ZenHub**](https://www.zenhub.com/)
