### ISSUE TITLE
State income doesn't have the option to add quantity

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#125]
When asked if the family receives state income, it is just a Yes/no question.
However, another field asking "How much?" (fill in the blank) should automatically appear when choosing the answer "yes".

**Comment by stacylorraineprendeville** [comment]
@aprojas What exactly happens in the app here? Please confirm....

**Comment by aprojas** [comment]
The question is "Does your family receive state income?" 
The only possible answers are yes or no.
But you don't have the option to fill in how much money you receive IF you choose YES.

**Comment by aprojas** [comment]
IF you choose YES, you should have another field to write how much state income you receive. Just like the "OTHER" feature that we said before.

**Comment by stacylorraineprendeville** [comment]
@aprojas exactly which survey? AND for how long has it been like this? We have not made any changes (I think) so this is maybe something that has been like this a long time

**Comment by aprojas** [comment]
I tried this with the Elmira survey. 
![2019-02-13](https://user-images.githubusercontent.com/44477708/52738701-f9e6a200-2fad-11e9-92d6-c2edac372707.png)

**Comment by aprojas** [comment]
I'm not sure for how long, but I just tried it again and it is still like this. However, for the spanish surveys this is not like this.

**Comment by stacylorraineprendeville** [comment]
@aprojas we do not understand the definition here.....

Are you saying there is a difference between the English and Spanish survey?

Regarding Other and Form logic - We do not have the logic to add another field when other is selected. We want it BUT as it was not in the previous app and requires both back end and front end work we have not been able to assign priority to this. We are also in effect changing client surveys when we do this - It will affect the CSV potentially. It has implications - It is partially groomed for inclusion in upcoming sprints.

**Comment by aprojas** [comment]
I understand that we do not have the "other" logic yet. Therefore, we need to meanwhile adapt the question. 

For example, the Spanish survey reads: Si recibe ingresos transferidos por programas del Gobierno, ingrese el monto mensual.

In English, it should be: If you receive revenues transferred by government programs, please enter the monthly amount.

**Comment by stacylorraineprendeville** [comment]
@aprojas Here can you provide a full list of surveys where this is happening - Or is this just for Elmira?

**Comment by aprojas** [comment]
This is just for Elmira. But nevermind, this is irrelevant now because it is the exact copy of the survey in the Stoplight Mobile. I'm moving it to Closed!

@stacylorraineprendeville
