### ISSUE TITLE
General amends for solutions module

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1254]
**Details page:**

- [x] Poner la organización hacia la izquierda y el país hacia la derecha
- [x] Hacer el tag de Tipo de solución con el mismo tamaño que el de dimensión e indicador
- [x] Que el tag de tipo de solución esté alineado con el borde a la derecha
- [x] Si es detail page, sacar el título Content: ya que se entiende que es el contenido de la solución. Ese título solo debería ser para crear o editar una solución.
- [x] Ahora mismo me aparece un scroll bar para ir hacia la derecha, eso se puede quitar?
- [x] Poner por lo menos algún espacio en blanco debajo de la última parte, que sería el Contact information. Porque ahora está muy pegada esa parte con el footer

**Solution form:**

- [x] Acercar más el nombre de la Organización al switch, está muy alejado.
- [x] When I'm writing a solution, and then I change the language of the platform, all of my answers are deleted and I have to fill it out again
- [x] Cuando subo archivos no aparecen las 3 imágenes estándar que habíamos buscado de PDF, PPT, DOC
- [x] Cuando termino de publicar una solución, me tendría que llevar a los detalles de esa misma solución, no al cards list de solutions.
- [x] Al editar una solución, cuando hago clic en CANCEL, no pasa nada
- [x] El idioma de las opciones de los selectores debe ser igual al idioma de la solucion.

**Cards list:**

- [x] El banner creo que debería entrar más hacia la izquierda.
- [x] En el card detail, cambiar el tamaño de los amount of views y el país a número 14

**Permissions**

- [x] Creo que Diego en la base de datos cambió la organización de algunas soluciones, de FP puso a hub, pero ahora cuando entro como hub, veo que en teoría yo escribí algunas soluciones, pero no puedo ni editar ni eliminar.
- [x] Ya probé creando una solución como hub y no puedo editar o eliminar. Eso habíamos quedado así? Creo que la verdad no queda tan bien.
- [x] En una solución que cree como hub, queda raro porque hay un scrollbar en el medio

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5e3fbc4e-5618-4ba0-8508-79b196b03863)

**Comment by aprojas** [comment]
- [ ] When I upload two pictures, and publish the solution, it looks like one of the pictures are duplicated and deletes the second one.
- [ ] When I choose many indicators, it should get stacked below the other tags and not overwrite the content

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f7af752a-3453-46b4-96d2-fa7606947d42)

- [ ] Align the dimension and indicators to the top of content
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d417b812-d2f6-4baf-bdb8-d38870745c63)

- [ ] If I choose to align my text in the text editor to "Justificado", it changes while editing, but when I save the solution, it shows me aligned to the left again.

@JDelPuerto

**Comment by aprojas** [comment]
- [ ] No veo que esto esté alineado al contenido. Capaz porque no tiene un tipo de solución?
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/daa3d8f7-e0bf-46ca-8bfc-bfa980babff3)

- [ ] Si es que no se decide mostrar la organización, el país debería estar alineado en el mismo lugar
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/cf7eeb16-fc66-4e74-83ba-074f30ea08de)
