### ISSUE TITLE
Finished survey error

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#128]
I finished and saved a survey. But when I wanted to leave the section of the surveys, it said that if I left all of my data would be lost. This is confusing for any user because it makes you think that you didn't correctly save the survey. However, the survey was already saved. 

![2019-02-05 4](https://user-images.githubusercontent.com/44477708/52275714-155b0880-292f-11e9-988e-37a4f72a5802.png)

**Comment by gigerbytes** [comment]
Resloved if #115 implemented

**Comment by gigerbytes** [comment]
@pA1nD pls check that this does not occur anymore.

**Comment by pA1nD** [comment]
I can't validate if that's correct. For me it still seems to show. (Maybe related to the other issue.

**Comment by gigerbytes** [comment]
@pA1nD Only related in the sense that the draft is not deleted / reset I think.
