### ISSUE TITLE
Improve Print option 

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#129]
When wanting to print the life map, the last part fits only one line and makes it print a whole page unnecessarily. Can it change somehow to make it fit only one page?
![2019-02-05 6](https://user-images.githubusercontent.com/44477708/52276305-9cf54700-2930-11e9-962f-51e4988f3828.png)

**Comment by stacylorraineprendeville** [comment]
@aprojas So it wasn´t really working before was it ;)

**Comment by stacylorraineprendeville** [comment]
@aprojas here I have to ask what is the plan for GECO and their oversized titles?

**Comment by aprojas** [comment]
It wasn't showing the last titles of the indicators, but, it's still how clients need it. We just need to improve this. Maybe we can talk about it more thoroughly?
@stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
I am closing this @aprojas we have a Spike - It will be a large task with a technical specification created during this sprint.
