### ISSUE TITLE
Create Projects Filter

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1303]
-- Has to support the:
- "All projects" option
- Only 1
- Multiple options.

**Comment by JDelPuerto** [comment]
Close this issue if #1304  or #1305 are working

**Comment by aprojas** [comment]
En el dashboard y family list, si elegís un org en el filtro, después en el filtro de proyectos te debería después mostrar solamente los proyectos asignados a ese org

@JDelPuerto
