### ISSUE TITLE
Removing a family member keeps it in the redux store

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/stoplight-web#132]
### Problem:

Creating two family members and later removing the app keeps the second family member in the redux store. Eventually this would then be sent to the server?

### Solution:

When changing the family members count, the exess family members should be removed.

**Comment by gigerbytes** [comment]
When a user initially sets the family members to a value > 1 and continues. then goes back and changes it to 1, the old values still persist.

Issue is because the redirect to the map skips updating the redux store.
