### ISSUE TITLE
Modify Operations overview component to show surveys per snapshot number (according to design)

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1418]
Modify Operations overview component to show surveys per snapshot number (according to design)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/c0bb54db-7cd4-48e1-aeb9-d96bcc3fbfc1)

**Comment by Guillecaba** [comment]
Modify list operations endpoint to classify surveys per snapshot number
We should show:

Total amount of surveys (like now)
Amount of baseline surveys (1st)
Amount of follow-up surveys
If the org/hub no tiene retakes, no muestra la leyenda y solo debe tener la línea verde.

para probar un user sin retakes, es necesario crear un user nuevo, entrar con el usuario org/org crear un usuario que tenga rol facilitador
logear con el usuario nuevo, tomar y guardar una encuesta nueva e ir al dashboard
