### ISSUE TITLE
Make family overview (lifemap in detail) responsive

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1426]
- Family name and banner should be the same as  family's profile ( create a generic component for this) 
- Fix tabs distributions when a famliy has too many snapshots taken ( take for example Fake Survey Generator family)
- Make sure that indicators  name are displayed properly, try to fix the indicators names so they  always are visible

**Comment by aprojas** [comment]
Minimize the fonts of the survey number titles, just like the fonts in the tabs.
@tomassilgueira

**Comment by aprojas** [comment]
@tomassilgueira 

The sizes of the titles in the comparative view have to be the same as the ones in the tabs. That was the same thing I wrote in the previous comment.


![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d16ea1c7-b0cb-47c0-b0f9-5fe74f770677)
