### ISSUE TITLE
Change Map responsive view (mobile and tablet)

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1444]
- Move upwards the Map title
- Leave only 2 filters visible always: Survey and Indicators (with the colors checkbox)
- The rest of the filters group them in a "More filters" button, similar to the Reports tab.
- Move the map below the filters
- Keep the clusters switch on the right and the total families on the left - on the same row
- Make sure the search box works.
- Maintain the satellital and normal map view
- Make sure that the Family name box is not very big

Obs: Let's try to see how this looks for the tablet view, if not, change the position of the filters to the right.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/60369c2c-bbe7-4ad2-a366-c4fdb781aa32)

**Comment by aprojas** [comment]
1. When I filter per org, the survey is reset to the first one.
2. I cannot open the Facilitators filter list

**Comment by JDelPuerto** [comment]
The fix  it's ready for testing @aprojas
