### ISSUE TITLE
Missing frame in life map process

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-web#146]
Views have missing frame around.
This has been created numerous times and has disappeared again!
This was the original idea below . Though please use what is already created in code rather than recreate.
![Screen Shot 2018-11-26 at 21.43.06.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/212a6f9d-1cf9-48a0-95ae-66b02d473199)

**Comment by stacylorraineprendeville** [comment]
This has disappeared again throughout the whole life map process.....So I have converted this issue into one of "all screens"
