### ISSUE TITLE
 Adjustment for retake button on responsive

### ISSUE THREAD

**Issue by Guillecaba** [FundacionParaguaya/stoplight-web#1460]
For s5, iphone 6/7.

in SPANISH

![s5.png](https://images.zenhubusercontent.com/5ea6e987861fca48437430e4/7587d58f-2b9c-4f1d-bf6a-ddcd17bf403f)

**Comment by aprojas** [comment]
Can we make it a little bit thinner? 
It has too much white space. @Guillecaba 
Compare to the space of "Datos socioeconómicos"

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/74028ecd-343b-4a53-8110-026806a3ce5a)
