### ISSUE TITLE
Enhance hub's view responsiveness

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1463]
- Ensure filter and button separation
- Add hub modal and permission modals  need to look always like modals

**Comment by aprojas** [comment]
1. Show all Hub's name
2. Show limited characters for the description and then add "..."

@JDelPuerto 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/77b994c4-e2e3-469f-9f92-8627fa11e3dd)

**Comment by JDelPuerto** [comment]
Para verificar ingresar como el user: admin.
Los vista de hubs debería ser utilizable para dispositvos móviles incluidos el S5, esto implica asegurar la separación y el funcionamiento correcto del filtro y botón de agregar hubs,  la columna del nombre y la descripción del hub  cuentan con un ancho mínimo de manera a siempre a mostrar algo de información al usuario.
