### ISSUE TITLE
Change Activity Feed component

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1465]
The idea is to move the Activity Feed to the left hand side of the dashboard. There will be a button that indicated the Activity Feed on the left, like the image below:

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e3280df6-b67b-470c-bcf4-e9bbaa35837c)

Observation: when an user hovers on the button, the tooltip should read "Activity Feed"

Then, by clicking on the icon, a new component should slide open from the left to the right. This will make the complete dashboard also move to the right.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/850e2ed9-d3e5-4eb7-ac6d-69c2e72f5692)

Observations: 
- Font size 12 for text
- It should be possible to scroll down to see more
- Show at least 15 activities
-

**Comment by aprojas** [comment]
**Text for first survey:**

`John Smith took a baseline survey (N°1)!`

**Text for next snapshots of the same family:**

For second snapshot:
`John Smith took a follow-up survey (N°2)! `

For third snapshot:
`John Smith took a follow-up survey (N°3)! `

And so on...

SPANISH

`¡X X tomó su línea de base (N°1)!`

`¡X X tomó su encuesta de seguimiento (N°2)!`

And so on....

**Comment by JDelPuerto** [comment]
Consideraciones: el  feature no quedó exactamente igual al diseño, se decidió usar fondo gris, descartar la línea vertical y usar líneas de separación horizontales, todo el título aparecerá en negrita.

Se deben listar 15 actividades que deben ser accesibles scrolleando

Probar el feature con distitntos roles (usuarios)

admin/admin  (ROOT)
hub/hub (HUB_ADMIN)
org/org(ORG_ADMIN)
demo/demo (SURVEY_TAKER)

**Comment by Auxi9** [comment]
No se visualiza el tooltip.

**Comment by aprojas** [comment]
Comments to improve:

1. Solution text is not the same as the design. It should be Title of the solution instead of Facilitator, and if the title is very long, then it should be followed by "..." . Also, it should be Uploaded by: hub instead of origin. ORIGIN is only important for a new survey.

2. Priority should show the name of the indicator (see design) and not the Facilitator. Origin is OK because now we have the option to add it from the mobile too.

3. Make the icons aligned to where the Activity Feed title begins. But don't move the texts, in this way there will be a little more space between the icon and the text.

4. When I open the Activity Feed, it takes half of the logo space. 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/54353a1a-5925-467a-bc11-a77fd63343e2)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/346a3c40-5f9d-4427-adcb-ad9faa1e7eda)

**Comment by aprojas** [comment]
Add numbers in followups, just like in baselines. @diegotorrespy 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5dc826b6-4afc-4ba8-811e-a017babd9f4e)
