### ISSUE TITLE
Make User's tab responsive

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1466]
- Minimize the blank space between titles and filters.
- Verify that the banner is properly shown
- Show the Add User as a modal (width on the sides)
- Add a minimum of pixels so that the username is shown and at least some part of the Name.

**Comment by Guillecaba** [comment]
usuario admin/admin

usar como ejemplo los espacios y el tamaño de los modals en vertical y horizontal, que entre en la pantalla y no esten pegados a los extremos
 
Probar en iphone 6/7 Galaxy s5
