### ISSUE TITLE
Make Organization's tab responsive

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1467]
- Verify all filters and Add Organization button
- Check it's the same for Organization read only in Admin access
- Minimize blank space between titles and filters (See Hubs tab)

Correct typo in title (English)
`Add an Organization`

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5eeba6c0-96c0-4450-9091-11e3c2daaf35)

**Comment by Guillecaba** [comment]
usuario hub/hub

usar como ejemplo los espacios y el tamaño de los modals  del modulo de hubs, en vertical y horizontal, que entre en la pantalla y no esten pegados a los extremos
 
Probar en iphone 6/7 Galaxy s5
