### ISSUE TITLE
Change style in Solution header

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1474]
1. To try to make it more appealing, we could try to place all three components: org name, country and solution date in the same row and each with icons.

2. Also, make sure the date in English is with only one digit like: Aug 8, 2020 instead of Aug 08, 2020

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d0efc4ca-7b6f-41b9-a1e2-bdf64fa90af1)

**Comment by tomassilgueira** [comment]
**Cómo testear?**
Ingresar a la vista de "banco de soluciones" desde el header del home, luego, seleccionar una solución y verificar que la organización, país y fecha se muestren correctamente dentro del header, así como los botones de acción (eliminar y editar) para cualquier resolución.
