### ISSUE TITLE
Make Projects page responsive

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1475]
- Projects tab when logging in as Org
- Projects read only when accessing as a Hub

**Comment by Guillecaba** [comment]
usuario intercative_org/123456

usar como ejemplo los espacios y el tamaño de los modals de hubs, en vertical y horizontal, que entre en la pantalla y no esten pegados a los extremos

Probar en iphone 6/7 Galaxy s5
