### ISSUE TITLE
Bug with date filters show different total of families

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1479]
Choose Date Range: 
From: November 1 
To: December 23

### Amount of families: 162

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/32157387-8b7c-4437-b1dd-50a0d09d3446)

### Amount of families: 160

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/41ed4934-f206-4a4e-9d38-1a568cc2d67a)

**Comment by JDelPuerto** [comment]
The original problem of this was  duplicated snapshots for two families those snapshots were incorrectly label as "last".

We created a server [ticket](https://app.zenhub.com/workspaces/stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/stoplight-server/2073)  to fix any stored data problem
