### ISSUE TITLE
List offline maps

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1484]
A feature where Root Admin and PS team has enabled the option to add offline maps for Hubs and their Organizations.

Available for users:
- Root Admin
- PS Team
- Hub Admin

### STEPS

1. Click first on the icon next to the arrow (map icon)

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/06aeafec-59d4-45fe-b704-6c70aa13bba3)

**icon**: 
```
<span class="material-icons">
public
</span>
```

2. After clicking on the icon, it should take the user to a new screen where:
- You can select the area for a new map
- You can see your existing offline maps
- You can edit your existing offline maps

**Obs:** Show breadcrumb: Organizations > Offline Maps

3. In that new screen, the main section should show a map (with the user's location) where the user can select the area for a new offline map, and below, a field where the user can add the offline map name. After selecting/completing both, the user can click on the "Add new Offline map" button.

Below this, there will be a list of existing offline maps, and whenever the user adds a new one, the offline map will be added to the list (below).
The list can be similar to the users list, but just showing the Name of the map, the edit and delete button.

**Ideas:**
- Based on the size of the map, calculate the weight.
-

**Comment by JDelPuerto** [comment]
To test this log in as admin user, then Hubs -> Organizations -> Offline Maps List a

**Comment by aprojas** [comment]
1. Can the names be moved a little bit further than the icon? @JDelPuerto 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/eb948cb6-72de-4501-bfcc-af4484e03920)
