### ISSUE TITLE
Nuevo tipo de Usuario DIY

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1485]
Nuevo tipo de Usuario DIY

Agregar acceso:
-- Solamente Perfil nuevo y Support

**Comment by Auxi9** [comment]
No me parece correcto que se autocompleten estos campos. 
![image (9).png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/3405091f-0694-4e3b-b467-024c2ba5e59c)

**Comment by aprojas** [comment]
At the moment it has the option to go to the Dashboard and also the surveys page. @tomassilgueira
