### ISSUE TITLE
Nuevo vista de Perfil: My Profile 

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1487]
Nuevo vista de Perfil: My Profile

-- Verificar parte Family Details/Socioeconomic
-- El botón "Completar Semáforo" solo debe aparecer al perfil nuevo DIY, si tiene la opción de skip Stoplight
-- Que pueda editar los Family Details. Solamente ReadOnly para socioeconomic, no poder editar.
-- No tener acceso a ningún dashboard, ni poder hacer clic en el isologo del Stoplight. 

## PERFIL

1. **Tab**: Mi Perfil
2. **Mostrar**:
- TAKE OUT navbar
- Family Name
- Organization
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f7666dcc-d7d7-4f88-aaee-32aa8a433676)

- TAKE OUT EDIT BUTTON for Family Details
- TAKE OUT socioeconomic section

- ADD "Completar Semáforo" button. Button should be in the middle of the banner, and take out the other text.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/a1eaef89-8fa3-4572-9676-114145e005b8)

- Show images + button of add images *** At the moment, only add and show previous images.
- Show signature + button to edit signature
- Show Notes component

**Comment by JDelPuerto** [comment]
Credenciales para probar la nueva vista petergreen pass: 123456

Este nuevo usuario  solo tiene acceso a la vista "My profile"

**Comment by aprojas** [comment]
It looks so good!!

1. Add images feature is not working
2. Add notes should be enabled
3. We should add the option to add more priorities

Also, this survey does not have it, but when the survey has the signature option, will it also appear? To edit or add?
@JDelPuerto

**Comment by JDelPuerto** [comment]
Ready for testing @aprojas

**Comment by aprojas** [comment]
The pictures component is saving vertically and not horizontally. @JDelPuerto

**Comment by aprojas** [comment]
The pictures component is saving vertically and not horizontally. @JDelPuerto
