### ISSUE TITLE
Internal server error on Household

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#149]
When I clicked on my household to view the survey I took. This error appeared.

![2019-02-18 7](https://user-images.githubusercontent.com/44477708/52975456-6691e000-33a4-11e9-82e9-261b05ba60cd.png)

**Comment by aprojas** [comment]
https://demo.povertystoplight.org/error.html?id=1550581251808

I entered in demo.povertystoplight.org
with demo-demo
hub-hub
org-org

And the same error appeared when clickling on Ana Py Rojas

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/fp-psp-frontend #314](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/314) via [**ZenHub**](https://www.zenhub.com/)
