### ISSUE TITLE
Fix bugsnag configuration

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1494]
Currently not all error are being caught by bugsnag I suspect that it's related  to allowing bugs from just one URL (producition).

Make sure bugsnag it's catching  bugs from production, demo and app enviroments, for testing porpuse you could catch some error from your local setup but then disabled that

**Comment by Guillecaba** [comment]
@JDelPuerto 
Errors can be created from the production environment, blocking requests with the developer tools.

Now catch only errores in platform env

**Comment by JDelPuerto** [comment]
Seems to be working pretty well
