### ISSUE TITLE
Static dashboard section

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1498]
Create a new  section according to design (pending)  to obtain  the data a new graphql query will be use (service pending too)  

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f9e2bec8-62b7-468f-b4a2-92b90f1031bf)

**Comment by Auxi9** [comment]
Creo que los números deberían quedar alineados.

**Comment by aprojas** [comment]
Make sure the numbers and titles are exactly aligned:

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b7ebd2e8-4c54-4b99-97bc-7bdf456bd3b8)

Also, can the transition when the data of Stoplights return, be similar like the dimension animation in the dashboard?

@tomassilgueira

**Comment by aprojas** [comment]
Can the transition when you close the extra information in "Stoplights" be smoother?
Similar to the transition when you close a dimension in the bar chart.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/c07085a0-8989-4631-8c08-0574437ed9ce)


![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/7adc04aa-3a39-4777-9c4a-2b8511a78b83)

@tomassilgueira
