### ISSUE TITLE
Bug - Family Members Screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#150]
I enter the family members screen on the Irradia survey.

First I select I have 20 family members - then I select I have 1
When I select 1 I cannot use the continue button - I am not allowed to go forward
To go forward I need to select 2 people.

This is a strange bug - sometimes it is possible - sometimes it is not

**Comment by Danman7** [comment]
This is fixed in the refactor.
