### ISSUE TITLE
Family profile improvements

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1518]
1 - El titulo se podría alinear con el valor para priorities y achievements
![image.png](https://images.zenhubusercontent.com/5c9ced779a9dfd5292735bfa/2c1f54d7-790c-4e4f-a88d-d8b6c354e86f)

2. La firma aparece con un zoom enorme para firmas que ocupen todo el espacio vertical
![image (1).png](https://images.zenhubusercontent.com/5c9ced779a9dfd5292735bfa/bcf6ac5b-b82d-4122-98cb-ed9df5d653e8)

**Comment by aprojas** [comment]
About Number 1, this was not talked about. The indicator rows or dates row should not have been moved, and not be aligned to the middle. Please keep the design as it was before and just move the titles a little bit to the sides. 
@tomassilgueira 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/44a0082f-151c-4f0b-a200-d159f261f9a3)
