### ISSUE TITLE
Disable form autocomplete for create users screen

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-web#1524]
Disable form autocomplete for create users screen

**Comment by aprojas** [comment]
This is still happening for the Name field. And it shows me the name of a credit card I once saved. Does it have to be erased too?

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/24578aea-c3b2-477a-ab58-8944bf304c7c)

@tomassilgueira
