### ISSUE TITLE
Count of baselines in static dashboard is incorrect

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1531]
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/4bb8987b-4358-4a95-a53e-8dc5094f9f22)

The baseline is higher than the actual number of families. It looks like it is adding the baselines + followups. And it shoes the "only socioeconomic" numbers when there isn't.

**Comment by Auxi9** [comment]
@aprojas  > Una familia con datos inconsistentes https://testing.povertystoplight.org/family/1941   
![image (11).png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/fd3cb8ac-0d0c-4b98-9229-46bf97217986)
