### ISSUE TITLE
Select all for Drafts list

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1545]
## Idea

Add a select box for all drafts (like in the Gmail)
And a button that says: Select All
And at the right, add a button that says Delete, which will appear if you select more than one draft

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/eeab833e-073c-4790-87fa-a5b3de5b9892)

## Observations

- Available for Facilitators and Admin Facilitators.

**Comment by aprojas** [comment]
When I select the family/ies, and the delete icon appears, the search box moves a little to the right to accomodate the button. Can we maybe shorten the search field so it doesn't have this strange transition?

@Guillecaba

**Comment by Auxi9** [comment]
Luego de eliminar las encuestas  que estan en pendiente no se visualiza el mensaje: "Drafts successfully deleted." "Borradores eliminados correctamente." @aprojas @Guillecaba
