### ISSUE TITLE
Possibility to delete priorities

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1568]
Add a confirmation modal to delete priorities

For:
Facilitator
Facilitator Admin
Family User

**Comment by JDelPuerto** [comment]
You'll find the button to delete priorities inside of each priority  in the family profile.

That button should not appear in  Details view

**Comment by aprojas** [comment]
1. Can we align the buttons to the right? One below the arrow icon, and move them more closer together, just like the distance between the buttons in a Solution article

@JDelPuerto
