### ISSUE TITLE
Create a modal to edit priorities

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1569]
Only months field should be mandatory ( if you can make only this field needs to be mandatory when adding priorities)

For:
Facilitator
Facilitator Admin
Organization Admin

Example for Update

{ "query": "mutation updateSnapshotStoplightPriority($priority: PriorityDtoInput) {updateSnapshotStoplightPriority(priority: $priority){successful}}", "variables": { "priority": { "id": 1755, "reason": "test", "action": "test", "months": 12345 } } }

**Comment by aprojas** [comment]
When I want to edit a priority, the months are not previewed. Only the other 2 previous answers.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/497be99b-c0d5-45d4-a883-385a8f2d84d6)

@tomassilgueira
