### ISSUE TITLE
Amends for move component

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1582]
1. Make the modal a little bit longer

2. Show the button Save.

3. Always show the fields of Organization and Facilitator. But the list of Facilitators will depend on the Organization selected.

4. The projects field should take into account which Facilitator was selected, so it will only show the projects that are assigned to the Facilitator.

5. Limit the row numbers of elements of dropdown before showing the scroll. Or try to overflow the select component outside the modal window.

**Comment by aprojas** [comment]
I moved this family to a new organization "Testing Features", selected the Facilitator "Anatest" and the project "The Elderly Group", but in the main profile, it still appears the old project.

@Guillecaba 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/caff7dc9-35f7-40ae-bcc6-99453e7e0cbd)

**Comment by Auxi9** [comment]
El comentario que dejo AnaPau arriba todavia no se encuentra solucionado. @Guillecaba

**Comment by Guillecaba** [comment]
> I moved this family to a new organization "Testing Features", selected the Facilitator "Anatest" and the project "The Elderly Group", but in the main profile, it still appears the old project.
> 
> @Guillecaba
> 
> ![image.png](https://camo.githubusercontent.com/09e10f43dd695e0980a1572789205305853c8f08dd1a3caf29c20c7e43ebe764/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563343863386462663838333438366364653330643834392f63616666376463392d333566372d343061652d626363362d393934353365376530636264)

Esto ya esta listo, se hizo un fix en el backend
