### ISSUE TITLE
Show economic and family data per snapshot 

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1594]
Add that information in every snapshot detail view. Also from now on we should show all snapshot not just the ones with stoplight sections

**Comment by JDelPuerto** [comment]
From now on Snapshot's details view should be always visible even if the family has just one snapshot without it's stoplight section.

Data will not be editable

**Comment by aprojas** [comment]
BUG:
1. When in a new followup survey I add more members, it will replicate in all previous snapshots. Not only in the last one.
Check family: Stoplight Demo Harriette from facilitator: Anatest
I added one new member in the 3rd snapshot, and its details show in every one.

@JDelPuerto

**Comment by aprojas** [comment]
The 1st bug is not solved yet.

@JDelPuerto
