### ISSUE TITLE
Check color's accessibility

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1610]
https://webaim.org/resources/contrastchecker/

**Comment by ivanarieldmc** [comment]
The contrast ratio of the forms inputs are 1.1:1. This does not comply with the Web Content Accessibility Guidelines 2.0 

> WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. WCAG 2.1 requires a contrast ratio of at least 3:1 for graphics and user interface components (such as form input borders). WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.
> Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger.
[https://webaim.org/resources/contrastchecker/](Contrast tool)
[https://www.w3.org/TR/WCAG/](WCAG 2.0)

![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/67319a51-21a2-49ca-b448-e1196cec838e)

**Comment by ivanarieldmc** [comment]
The "Continue" button contrast ratio does not comply either.

![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/2fa17f43-3e75-4893-89dc-a6bc50068a3c)

**Comment by ivanarieldmc** [comment]
The red indicators of required inputs pass at least the minimum contrast ratio (AA).

Below a link to more info:
Contrast Ratio
[https://webaim.org/articles/contrast/](url)

![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/0d33852a-641b-4dd1-8c62-30219425b532)
