### ISSUE TITLE
Add option to delete (logic) a survey

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-web#1617]
Add option to delete (logic) a survey.
Add the trash icon at the right hand bottom.
Add the confirmation modal when clicking on the button. 
Add snackbar for validations messages.

Users allowed to perform this action:
- ADMIN

**Comment by aprojas** [comment]
The shadow behind the delete button is not a perfect circle.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/15910300-f663-46c5-a84f-edb13c87a106)

@tomassilgueira
