### ISSUE TITLE
Research a way to calculate map size

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1637]
We need to stop users from creating maps too big to  be useful

**Comment by JDelPuerto** [comment]
Map diagonal limit it's 575km because we already have one map that size  (Antioquia)

**Comment by Auxi9** [comment]
No me permite agregar ningún mapa. @aprojas 
![image.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/8def98fc-3041-485f-816c-405c95f505e8)
