### ISSUE TITLE
Strange glitch in the dimensions of dashboard

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1638]
From Admin/Admin

1. Select Hub
2. Select survey version

When I filter by a specific survey, the dimension sector filters for the first seconds but then it shows all dimensions at once.

**Comment by JDelPuerto** [comment]
Problem it's that a previous asynchronous call  data overrides latest call data, to prevent this we need to cancel all previous calls before making new ones

**Comment by aprojas** [comment]
I don't know if it's a problem with my computer, but when I select a hub and then want to select a survey version, no survey version appears!
@JDelPuerto 

Even if I select an organization..

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/6ca462fd-3d60-4fb9-a352-0e69509a731d)

**Comment by JDelPuerto** [comment]
@aprojas  @Auxi9  Please check if every filter it's working as intended.

Filters list:
- Hubs
- Organizations
- Surveys
- Projects
