### ISSUE TITLE
Incorrect behavior in breadcrumbs of offline maps

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1642]
**Steps to reproduce:**

1. Login as admin/admin in PLATFORM.
2. Go to Hubs list
3. See organizations of one hub
4. Select offline maps icon for one organization
5. Then go back to the organizations list by clicking ON the Organizations name in the breadcrumb

Problem: It will show you ALL the organizations of ALL hubs, not only of the hub that was previously selected.

**Comment by Auxi9** [comment]
Esto sigue pasando @aprojas @JDelPuerto 
Pasos: 
Logueada con Admin: ---> Hubs / en la tercera posicion esta el icono de cerrito entro a sus organizaciones, solo tiene una organizacion. doy clic en LISTA DE PROYECTOS la navegacion queda como Hubs>Organizaciones >  Proyectos. Doy clic en organizaciones se visualiza todas las organizaciones no solo el del hub seleccionado previamente.
![Selection_649.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/414942b6-e336-4a6f-9aeb-592a634699e1)
![Selection_648.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/d8514fba-5e4c-47fa-b318-c368889d583e)
