### ISSUE TITLE
Research audios size for survey builder

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1662]
Research ways of reduce audio size for the surveys.

Audios have .mp4 extension.

**Comment by ivanarieldmc** [comment]
The best way of reduce the audio size by lowering the bitrate is to go to 64Kbps. 

Tested on musics with a bitrate of 128kbps and 3.8mb size.
![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/756d999b-000c-4fc2-bc6d-c12a159f5efc)

The result was a 50% size reduction, with quality barely affected.
![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/0bbcfea6-7cb5-44e2-8399-e6810267d5b6)

Tested reducing bitrate to **_32-64Kbps VBR_** and **_32Kbps_** but the quality was severely affected.

The online page used was [mp3smaller.com](https://www.mp3smaller.com/)

The pages [OnlineConverter](https://www.onlineconverter.com/compress-mp3), [FreeConvert](https://www.freeconvert.com/mp3-compressor/download) showed same results.

Best results came from the page [YouCompress](https://www.youcompress.com/mp3/). It compressed at the same file size (did not specify bitrate) and maintained better quality.
![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/9ae164ed-2724-4f4d-8867-d5602749e41d)

**Comment by ivanarieldmc** [comment]
**Next test runned:**

Downloaded .mp4 file from server with size of 1.5mb. 
![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/bf175544-00ad-4b7e-9727-4c0008f2e111)

Converted to a mp3 file with a size change of 2.1mb.
![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/47d2c273-2977-4a7c-9ea8-53253373c7cf)

Reduced the file size with [YouCompress](https://www.youcompress.com/mp3/) webpage with a result of 65% reduction.
Final size 726,5kB.
![image.png](https://images.zenhubusercontent.com/60267c163a1b9d1e9b713007/166a2936-afeb-439c-aef3-f48f90a60878)

**Overall result: size reduction of ≈50%**
