### ISSUE TITLE
Fix stoplight broken for some cases

### ISSUE THREAD

**Issue by tomassilgueira** [FundacionParaguaya/stoplight-web#1727]
Problem was found in the philippines english survey
![image.png](https://images.zenhubusercontent.com/5f96d473764bd469741533bb/a3b03290-76ca-4675-87b1-d782fb3fff68)

**Comment by Auxi9** [comment]
Ok. Asi se visualiza despues del cambio
![Selection_783.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/65a77538-a36c-4a5a-b78b-ed62ddfe0c60)
