### ISSUE TITLE
Few edits for Support section

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1729]
- [x]  Change title:

ENG: Support articles from the Poverty Stoplight Platform Team
ESP: Artículos de soporte del Equipo del Poverty Stoplight Platform

- [ ]  Change text:

ENG: About the Web Platform

- [x]  Change text in button

ENG: Add an article

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d8072492-40b0-4232-a2df-552f1d072174)

- [x]  Change text to the name of collection: General questions
But this happens with all the collections.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/446ae88a-4a72-4674-bbc9-31a18517f320)

- [x]  Can we move the position of the breadcrumbs?
For me it was strange to see this position there..

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b1eb6c78-342f-4f48-9120-3bed21cf5c7b)

- [x] Can this also be clickable so it can take me to the main list of collections?

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/83482bb0-6633-46e4-93bf-222217ce1c88)

**Comment by JDelPuerto** [comment]
Start from  your work from this branch jdelpuerto-hid-interventions @Guillecaba

**Comment by Guillecaba** [comment]
![image (3)](https://user-images.githubusercontent.com/9329111/119566589-4dddb500-bd79-11eb-8532-dec2d3ae9ead.png)

Name of the article instead
