### ISSUE TITLE
Add preview for create intervention definition

### ISSUE THREAD

**Issue by ivanarieldmc** [FundacionParaguaya/stoplight-web#1731]

**Comment by Auxi9** [comment]
Bug al crear una intervención. 
![Selection_792.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/c8a5061c-c40d-4db3-a08e-1da714ab9a2b)

limitar caracteres
![image (11).png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/a83cd42c-47f8-4ee1-b8e2-e31d458c5ffa)
