### ISSUE TITLE
Changes to Intervention Definition

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1732]
## INTERVENTION FORM

1. The button can say: Add intervention form
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ff32bb45-77d4-4603-b622-2797524e1fb2)

2. Change to "Is this a general intervention?" when listing the core questions in the intervention definition.

## INTERVENTION IN PROFILE

1. The edit and delete buttons should be on the right hand side
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/11b6912a-5fe0-4102-b387-8a8b2746b5d7)

2. When there are more indicators and then starts listing below, can there be more space between one another?
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e7c83467-7318-4a39-9de1-f70d664951c2)

3. **BUG**: When I write a long text in the input field, the title of the question blends with the answer.
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/9c11e3de-5968-43f7-9784-e53a19ae9b72)

4. BUG: I edited the last question Training Type (took out the answer because it was optional) and the answer was still there when I opened the complete card. Does this mean the page should refresh to see the change? I think it should be the same behavior as the edit priority or Family details

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/9f3fb94d-071a-45a6-84f3-a044e1642e24)

**Comment by Auxi9** [comment]
los botones de editar y eliminar no se visualiza a la derecha. 
![Selection_826.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/a802cfba-b998-4e24-be64-828c2230f472)

**Comment by Auxi9** [comment]
![image.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/84792714-72d3-447f-9180-07650c293da0)
