### ISSUE TITLE
Skipped indicators still allow priorities

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#174]
@stacylorraineprendeville commented on [Wed Jan 30 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/403)

@stacylorraineprendeville commented on [Fri Jan 18 2019](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/291)

@aprojas commented on [Tue Jan 15 2019](https://github.com/FundacionParaguaya/MentorApp/issues/282)

[https://demo.povertystoplight.org/#families/687/snapshots/%0A%20%20%20%20%20%20772/indicators](url)

When clicking on a gray indicator, which means that this indicator was skipped, I can still have the option to add priorities (however, it's not a red or yellow indicator). It should just not give me the option to click on it.

**Comment by Danman7** [comment]
Fixed after refactor.
