### ISSUE TITLE
Failed check for Family user permission

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1742]
![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/3d4eca65-9348-4d63-96f3-d1e2c2a83cf2)

**Comment by JDelPuerto** [comment]
El error ocurría al abrir el modal de creación de usuarios, para testear podrías ir al ambiente de demo: https://demo.povertystoplight.org/
y utilizar estás credenciales dorcas_org/123456
