### ISSUE TITLE
Add unify families flow

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#1752]
1. Add unify modal confirmation
2. New icon next to "move" icon, when selecting two families to unify (see which icon)
3. It will be only possible to unify 2 families at once
4. See if in the modal confirmation we can show the name of the family that will be unified. Should be the name of the last snapshot taken.
5. Add snackbar confirmation

**Comment by JDelPuerto** [comment]
Para probar  logearse como el user admin, el icono para unificar las familias aparecerá solo al seleccionar dos familias.
Para que la unificación de familias sea exitosa las familias seleccionadas deberán pertenecer a la misma organización y haber tomado la misma encuesta

**Comment by Auxi9** [comment]
A modo de sugerencia creo que el mensaje deberia ser "Las familias...." o sino agregarle la s al mensaje ya existente
![image.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/7d6b5ba6-418f-485d-82dd-208e4c1c6cf1)

Se podría alinear los iconos ?
![image.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/143eeb3a-c731-4ed3-88bc-7e368c683a8a)

**Comment by Auxi9** [comment]
![image.png](https://images.zenhubusercontent.com/5ff710c674fab4eb98b86655/160da9e5-9c5c-43f6-b214-9d7b75f73279)
