### ISSUE TITLE
Changes in Guatemala survey

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-web#1784]
Change the document indicator images:
SURVEY: Guatemala - Nelixia
indicator: documentation

RED:
![5Red.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d3faefb9-caf3-49c4-973b-e8af4892182d)

YELLOW:
![5Yellow.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/4d3c548e-ab80-4ec2-9a0c-3bdd3695578a)

GREEN:
![5Green.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/6638c912-1ec8-4ea5-aabe-a888a13ef763)

**Comment by ivanarieldmc** [comment]
Uploaded the images to the Amazon S3 bucket, replacing the wrong ones.
