### ISSUE TITLE
Answers are automatically selected (ACTIVATE)

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#179]
On platform, with the Paraguay Activate survey:

BUG 1: I do not select any option for my answers but they already appear with an option selected. For example, I didn't select anything for "Situación de la vivienda" but "Propia con título" was already selected. 

![2019-03-12 (4).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/bd8562e2-16f2-4512-9c34-07bc5218adfd)

BUG 2: Most questions are not mandatory when they should be. 
For example, I didn't write anything for "Jefe del Hogar" and I could still continue the survey.

**Comment by stacylorraineprendeville** [comment]
@aprojas We will not fix this as it does not impede the client AND we have the new release coming

**Comment by aprojas** [comment]
This is fixed with the new release.
@stacylorraineprendeville
