### ISSUE TITLE
Create summary view

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#1790]
Add checkboxes for all current surveys options that we support ( Sign support, picture support, interactive help, random order, hasQuestionsWithScore,) 

Should look like this
![image.png](https://images.zenhubusercontent.com/5c9ced779a9dfd5292735bfa/52ba65e8-f8c4-479e-af06-ade3b897409a)

**Comment by aprojas** [comment]
Can we take out the following options?

1- Random Order
2- Score

If a future partner wants this, we can add it as a support ticket.

@JDelPuerto
