### ISSUE TITLE
Lifemap Survey

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-web#18]
### User Story
As a Survey Taker / Mentor, I should be able to take a life map with a family. 
* I should be able to select the survey that the family should take from a list.

The survey should allow me to collect information of the following
#### Primary Participant & Family members
* Required details of the primary participant such as name, age, gender, document type, document ID and country of birth
* Optional details of the primary participant such as phone number, email
* Required details of their family members such as First Name, Gender & Birthdate
#### Family Members
* Required details of the family such as their Geolocation (if possible) and their country of residence
* Optional details about the family such as their address & postcode.

#### Socio economic questions
* The appropriate socio economic questions associated with the survey they are answering

#### Stoplight indicators
* The stoplight indicators associated with the survey they are taking

**Comment by stacylorraineprendeville** [comment]
@pA1nD How come this has been moved into grooming when it was part of a sprint?
