### ISSUE TITLE
Education section missing Activate survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#180]
On platform, Activate Paraguay survey.
The education section is missing in the Activate PY survey. But it is present in the mobile app.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy  can you confirm that this is becuase of the new online lifemap not working correctly on line?

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy can you confirm that this is becuase of the new online lifemap not working correctly on line?

**Comment by diegotorrespy** [comment]
@stacylorraineprendeville 

In this issue @aprojas is not talking about the new lifemap online but the current online survey. This last one does not have the support to ask for every member and that's why the Education section is missing.

**Comment by aprojas** [comment]
Hmmm true. I did this a long time before when I didn't quite understand it. We can close this since the current platform will never have this feature, right?

@stacylorraineprendeville @diegotorrespy

**Comment by stacylorraineprendeville** [comment]
@aprojas lets leave this open and check that it does when we make the switch to the new lifemap online

**Comment by aprojas** [comment]
This is available in the new platform web. I'm closing this!
@stacylorraineprendeville
