### ISSUE TITLE
Upper right hand icons disappear

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#185]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/487)

When I click on surveys, the icons of language, and logout disappear.
![2019-03-07](https://user-images.githubusercontent.com/44477708/54136336-58127380-43fa-11e9-82de-79a9b1ef14c9.png)

**Comment by Danman7** [comment]
They disappear because we have no access to the user name from surveys yet and the language selector isn't applied. We are tracking both of these.
