### ISSUE TITLE
A Blank space in dropdown list

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#186]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/488)

There's a blank line when clicking on a dropdown list. 

![2019-03-07 (1)](https://user-images.githubusercontent.com/44477708/54136557-ceaf7100-43fa-11e9-86c1-ff02f39a40aa.png)

**Comment by Danman7** [comment]
At a glance I would say this is related to #188.

@stacylorraineprendeville Could you check that issue and respond there. There is no empty space after refactor.
