### ISSUE TITLE
Select gender is not mandatory

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#187]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/489)

The select gender field doesn't have the asterisk. But it is in fact mandatory.

![2019-03-07 (2)](https://user-images.githubusercontent.com/44477708/54136891-5dbc8900-43fb-11e9-9e04-5bf7b9bc695d.png)

**Comment by Danman7** [comment]
Fixed after refactor
