### ISSUE TITLE
Bug: Cannot unselect dropdown option.

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#188]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/490)

If I select an option from some dropdown lists, I cannot unselect it even if it's not mandatory.

**Comment by Danman7** [comment]
@stacylorraineprendeville Unlike with the mobile app, it would be simpler for us to add an empty option like `--` than to unselect it when clicking outside the select while it's open (but we can do that as well). Can you specify which unselecting method you would like?

**Comment by javierpf** [comment]
As in #238, this can be solved after integrating all dropdown fields with react-select
