### ISSUE TITLE
Wrong image sizes in indicators screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#190]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/492)

![2019-03-07 (3)](https://user-images.githubusercontent.com/44477708/54143311-5354bc00-4408-11e9-9f63-eb2199e80cc6.png)

**Comment by Danman7** [comment]
Fixed after refactor. We now have a different issue that is tracked in another branch.
