### ISSUE TITLE
The whole text is not visible

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#192]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/495)

In some indicators where the text is very long, I cannot read the whole text. 
![2019-03-11 (2)](https://user-images.githubusercontent.com/44477708/54152688-9751bc00-441c-11e9-85d7-4b0b24821379.png)

**Comment by Danman7** [comment]
Fixed after refactor
