### ISSUE TITLE
Dimension Typos in FUSAI survey

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#193]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/496)

Health & Environment typo. The "H" should be upper cased. 

![2019-03-07 (6)](https://user-images.githubusercontent.com/44477708/54153131-979e8700-441d-11e9-898b-20d047242c7c.png)

Housing & Infrastructure typo. the "H" should be upper cased.

![2019-03-07 (5)](https://user-images.githubusercontent.com/44477708/54153166-a9802a00-441d-11e9-8ed9-78b2cfed29d5.png)

**Comment by stacylorraineprendeville** [comment]
@aprojas can you move this into the server repository

**Comment by aprojas** [comment]
Ok. But this was before in server repository and you closed it.

**Comment by stacylorraineprendeville** [comment]
@aprojas Is this still happening?

**Comment by aprojas** [comment]
Yes, I can see it in demo. Some titles of dimensions are repeated but because their written differently. 
Also, they appear in English, when it should be in Spanish!

@stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #743](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/743) via [**ZenHub**](https://www.zenhub.com/)
