### ISSUE TITLE
Indicators are not aligned

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#194]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/497)

Some of the indicators' names are not aligned.

![2019-03-07 (8)](https://user-images.githubusercontent.com/44477708/54153833-4394a200-441f-11e9-89d0-049fb3ca9189.png)

![2019-03-07 (5)](https://user-images.githubusercontent.com/44477708/54153845-4c857380-441f-11e9-9bb0-e5ca97955537.png)

**Comment by Danman7** [comment]
@stacylorraineprendeville Aligned to what? I don't see anything wrong in the screens

**Comment by aprojas** [comment]
We can close this since it's not relevant anymore right? @stacylorraineprendeville
