### ISSUE TITLE
New text blends with the field text

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#195]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/498)

This still happens.

![2019-03-07 (7)](https://user-images.githubusercontent.com/44477708/54153986-a71ecf80-441f-11e9-8768-0fb698d99e55.png)

**Comment by Danman7** [comment]
Fixed after refactor
