### ISSUE TITLE
Incorrect yellow color

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#196]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/499)

This is not the correct yellow color. 

![2019-03-07 (14)](https://user-images.githubusercontent.com/44477708/54154763-6d4ec880-4421-11e9-9c9b-a4de752cdc2d.png)

**Comment by Danman7** [comment]
We checked that we are using the correct color as the mobile app is using.

@stacylorraineprendeville @aprojas If that is not the right color please reopen this issue and specify the color hex (#something).
