### ISSUE TITLE
Bug: saving and going back in indicators section

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#198]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/500)

After writing down my 5 priorities, I clicked on continue but before saving and closing, I went back to change the level of the last indicator. when I arrived to the indicators list again, my priorities remained the same, but I could not continue because it said that I didn't have my 5 priorities chosen. So, in the end, I had 10 priorities.

---

@stacylorraineprendeville commented on [Thu Mar 14 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/500#issuecomment-473039355)

Issue moved to [FundacionParaguaya/stoplight-web #197](https://github.com/FundacionParaguaya/stoplight-web/issues/197) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Danman7** [comment]
We will fix this after we actually have minimum priorities in the refactor

**Comment by Danman7** [comment]
Fixed after refactor.
