### ISSUE TITLE
Bug: No indicators prioritized

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#199]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/502)

When I went to view my household, it appeared that I didn't prioritize any indicator.

![2019-03-07 (9)](https://user-images.githubusercontent.com/44477708/54155247-7db37300-4422-11e9-9ced-86e537ece7da.png)

**Comment by Danman7** [comment]
Issue moved to [FundacionParaguaya/fp-psp-frontend #341](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/341) via [**ZenHub**](https://www.zenhub.com/)
