### ISSUE TITLE
Bug: blank space in title

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#200]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/503)

There's a blank space in the first title of every screen

![2019-03-08 (3)](https://user-images.githubusercontent.com/44477708/54155331-a76c9a00-4422-11e9-8d5b-7f5d3069e0ea.png)

**Comment by Danman7** [comment]
Fixed after refactor.
