### ISSUE TITLE
Number of participants isn't in the first screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#201]
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/504)

Number of participants should be in the first screen just like in the mobile app

![2019-03-11 (3)](https://user-images.githubusercontent.com/44477708/54155556-25c93c00-4423-11e9-82ca-1a729ccec86f.png)

**Comment by Danman7** [comment]
This is fixed with the refactor.
