### ISSUE TITLE
Offline map did not load on first time

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#205]
I logged in and used the demo fundacion paraguaya sruvey.
The map loaded black as below.
I connected and then disconnected to the internet - the map appeared BUT it connected not to my real location - It connected to the centre of the offline loaded map?

![Screenshot_20190318-131709.jpg](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/d4eec86e-7f9b-498d-a46d-94242f3889ec)

**Comment by Danman7** [comment]
This is for the other repo and is no longer relevant as we don't have an offline map at the moment.
