### ISSUE TITLE
Manual App Testing Plan and Implementation

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#206]
Everyone make a survey in the office after the internal testing track - Stacy to instigate
Dan on each release to provide testing details to Ana and an overall QA Plan.

**Comment by Danman7** [comment]
@stacylorraineprendeville Where should this plan be published?

**Comment by Danman7** [comment]
Published here: https://github.com/FundacionParaguaya/MentorApp/blob/master/docs/test-plan.md
