### ISSUE TITLE
Ability to sticky to top not one list element but various

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#208]
In fields such as country of birth we add one country to be at the top of the list.

We have clients that would like to add 4/5 countries at the top of the list.

This issue is to estimate this in the App

**Comment by Danman7** [comment]
@stacylorraineprendeville @diegotorrespy We need a way to know which countries should be at the top. This will come in `surveyConfig` in each survey. I don't know any other field that uses this logic but country, so I will estimate for country only.

**Comment by stacylorraineprendeville** [comment]
@JDelPuerto ? Your thoughts - as you resolved https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/601

**Comment by JDelPuerto** [comment]
We solve that same problem but for economic questions I think they handle the list of countries in a diferent way  @stacylorraineprendeville

**Comment by JDelPuerto** [comment]
@zommerberg  You can trust that you will receive the list correctly ordered, as in Nationality field in Geco - Chile Survey

**Comment by zommerberg** [comment]
duplicate with #646 - mentorApp
