### ISSUE TITLE
Refactoring - Getting the Survey Live Online

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#212]
This handles the initial refactor to the point where the app is usable online for survey taking.

**Comment by Danman7** [comment]
At this moment we have done:
- Primary participant
- Socio economic screens
- Stoplight screens
- Location screen with working map
- Begin lifemap screen

I will create issues for everything else that is left.

**Comment by Danman7** [comment]
Refactoring is complete. App is online. We are tracking remaining issue.
