### ISSUE TITLE
Endpoint for editing skipped questions

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/stoplight-web#232]
In order to resolve #467 we need to implement and endpoint for answering questions after a snapshot is synced. @diegotorrespy What do you need as information from the front-end? FamilyId? Snapshot id?

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #573](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/573) via [**ZenHub**](https://www.zenhub.com/)
