### ISSUE TITLE
Dropdown list with keyboard option

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#238]
In the Dropdown list of countries, or any dropdown, one cannot search them with the keyboard. So if I select the key “P”, no countries that start with P appears. This should be an option for the future, as many platforms have it.

**Comment by javierpf** [comment]
As an option, we could add integration with react-select: https://react-select.com/home
It has filtering and type-ahead feature out of the box.

**Comment by javierpf** [comment]
I've created a new reusable Autocomplete component for this. Example of usage can be seen in the PrimaryParticipant form component
