### ISSUE TITLE
Error when not completing priorities

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#246]
Browser: Chrome

Steps:
1. I completed some priorities without writing anything, and deleted the month too (since nothing appeared as mandatory).
2. When I saved the Lifemap, an error jumped.
3. I went back to the Lifemap.
4. I clicked on the priorities I chose before (they had the blue dots) and completed them with some text.
5. I saved the Lifemap again and there wasn't any error. 

I suppose this is because there is a mandatory question (but it's not visual), but it nevertheless lets me complete the priorities without filling in the mandatory questions.

**Comment by Danman7** [comment]
Fixed in develop branch. Will be visible when merged with master.
