### ISSUE TITLE
Webpage had a shake when lifemap was saved

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#247]
When I saved and closed a Lifemap (in the process when the webpage was being refreshed), the webpage suffered a little shake before showing the survey section again. 

Browser: Chrome

**Comment by stacylorraineprendeville** [comment]
@javierpf try to reproduce only.

**Comment by javierpf** [comment]
@stacylorraineprendeville @aprojas Could not reproduce. @aprojas Can you test it again with the current instance in testing and report back?
