### ISSUE TITLE
Set up the Stoplights teams WIKI

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#250]
This issue is to liase with the team and setup the stoplight wiki.

What is contained
Create the WIKI
Make a general proposal on contents
Check in with Bjorn who has some existing documents in notion (he will be in PY sat - please arrange to meet)
Speak with all team members (one on one or group meeting) and assess needs.
Check in with PO

The WIKI should be the lifeblood of the team and the one stop for all requirements.

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #583](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/583) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pA1nD** [comment]
@JDelPuerto, after sitting together, we conclude as following:

(1) Make a suggestion to the team, where the wiki would be (probably: New Repo on GH)
(2) Make proposal on Contents (probably: General Overview, API Documentation, Releases)
(3) Speak with team and esp. PO.
