### ISSUE TITLE
Redesign: Primary Participant

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/stoplight-web#254]
Design: https://projects.invisionapp.com/d/main#/console/17060550/353873679/preview

Add validation for First and Last Names, Email and Phone.

@javierpf @stacylorraineprendeville There may be a better way to do the Date component. Let's discuss. We are considering: https://material-ui-pickers.dev/api/datepicker

**Comment by stacylorraineprendeville** [comment]
happy with that date picker

**Comment by stacylorraineprendeville** [comment]
If you can have one date field then great - earlier I was told it was not possible becuase very time consuming - but as per the app issue (in the backlog) one field is optimum - Please make sure it is Month, Day, Year this is the format we use for easy reading internationally

**Comment by stacylorraineprendeville** [comment]
@javierpf What is the validation utilised? I ask to make sure it reflects the exact same on the app

First Name
Last Name
Phone

**Comment by javierpf** [comment]
@stacylorraineprendeville 
First Name: not empty / not null
Last Name: not empty / not null
Phone: no validation at all.
@Danman7 can you confirm if this matches your validations?
