### ISSUE TITLE
Redesign: Overview - indicator filter

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/stoplight-web#264]
Design of the page: https://projects.invisionapp.com/d/main#/console/17060550/353873900/preview

This includes only the indicators filter.

@stacylorraineprendeville We need a UI for this.

**Comment by stacylorraineprendeville** [comment]
should have a ui mid sprint

**Comment by stacylorraineprendeville** [comment]
@javierpf invision is updated![Screen Shot 2019-05-01 at 17.10.08.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/99547e72-90ed-439d-9286-6f3147ec94b3)

**Comment by stacylorraineprendeville** [comment]
@javierpf hmm its a design flaw and not super problem but its a bit strange that the number of indicators disapears when it is the selected one - Would mean that we could say
All indicators (50) on first view - Instead of removing it - Your thoughts?

**Comment by javierpf** [comment]
@stacylorraineprendeville Fixed and available for testing
