### ISSUE TITLE
Redesign: Final screen 

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/stoplight-web#269]
Design: https://projects.invisionapp.com/d/main#/console/17060550/353873899/preview

We should use the pie chart as a reusable component.

**Comment by stacylorraineprendeville** [comment]
Is the print issue in a seperate ticket? @javierpf struggling to find it ....

**Comment by javierpf** [comment]
@stacylorraineprendeville I've created the issue 357 for printing the Final Screen
