### ISSUE TITLE
Improve Family Members

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#285]
Right now, we have a first Redesign for the Family Member screen. Although it looks fine, it does not quite match the base screen from the Invision project.
Please try to make it match the base screen: https://projects.invisionapp.com/d/main#/console/17060550/353873669/preview

**Comment by aprojas** [comment]
Hey guys! I can't see the invision project, so I cannot test it properly. Could you give me access?
This is my account: Ana Rojas - aprojas@fundacionparaguaya.org.py

@javierpf @gonzarodriguezt
