### ISSUE TITLE
Cross Browser Testing and Procedure

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#289]
This task is to research tools and approach for cross browser testing.

The result of the issue will be to have a working approach for how cross browser testing will be implemented for the front end of the platform. This could be the use of a tool such as Lamda test (please review appropriate tools) & the procedure in place for the "when" (during Review, on testing server?)

**Comment by gonzarodriguezt** [comment]
Discussing a with @javierpf, the best approach of `when` it should take part is doing Continuous Integration/Delivery, this will enable the automated tests to run _at the time_ as a new Pull Request is made, and the QA test will take part _after_ the Code Review pipeline.

**Comment by gonzarodriguezt** [comment]
This can be close now. Refer to #452.
