### ISSUE TITLE
Run cross browser checks on the lifemap online

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#291]

**Comment by gonzarodriguezt** [comment]
*Let's use Automate and run tests on Infrastructure:*
- Windows 10 (Firefox, Chrome, IE, Edge) - latest stable version or sth. (maybe automatically use "latest stable".
- macOS Mojave (Firefox, Chrome, Opera, Safari) - latest stable version or sth. (maybe automatically use "latest stable". (edited) 

*First testing szenario (rough draft):*
- Login as demo.
- Go to Surveys.
- Take survey (10 question survey - I think it's calld FuPa).
- Answer the questions. (no priorities)
- Go to "Households".
- Find family that you just created.
- Reveiw their information if it is EXACTLY as you entered it i the survey.

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt Please report back to why this is till open from Sprint 016

**Comment by gonzarodriguezt** [comment]
I'm not sure of where to upload the code, i will need to check it with @javierpf and also integrate it with the current CI setup.

Maybe we can close this and create a new one for that? @stacylorraineprendeville
