### ISSUE TITLE
Terms&Conditions / Privacy Policy not showing

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#293]
The text of the Terms & Conditions and the Privacy Policy is not available, and it combines with the colored designs. 

![2019-05-06 (1)](https://user-images.githubusercontent.com/44477708/57249457-014ca300-7013-11e9-80b3-423716f43ddf.png)

![2019-05-06 (2)](https://user-images.githubusercontent.com/44477708/57249463-090c4780-7013-11e9-9402-857faea58afb.png)

**Comment by javierpf** [comment]
@gonzarodriguezt I think this is not an issue, some surveys definitions in the testing environment do not include 'Terms and Conditions' nor 'Privacy Policy' texts. Please make sure it's just because of that!

**Comment by stacylorraineprendeville** [comment]
@javierpf @gonzarodriguezt Would be an issue we need to resolve asap if surveys are going out with T´s and C´s - Its a legal requirement - every survey in the app has them - They may be a default text - please check with @diegotorrespy

**Comment by diegotorrespy** [comment]
@stacylorraineprendeville @javierpf @aprojas 

As @javierpf  says, this issue only happens in the testing environment since these data are been 
deleted every week to clean up the testing database.
