### ISSUE TITLE
The (X) button does not appear in TC & PP

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#294]
The (X) exit button does not appear in the Terms&Conditions and Privacy Policy section. 

![2019-05-06 (2)](https://user-images.githubusercontent.com/44477708/57249542-39ec7c80-7013-11e9-9024-79cf1020a993.png)

**Comment by javierpf** [comment]
@aprojas I could not reproduce the issue. Can you please check again?
