### ISSUE TITLE
The D.O.B. should display an error message

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#295]
The D.O.B. should display an error message when you fill in an invalidate birthdate.

![2019-05-06 (3).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/63407998-5366-4c20-ae37-09d06292c7dc)

**Comment by javierpf** [comment]
@aprojas what's the definition of invalid date of birth?
Right now, we don't allow dates after today, but there's no validation that checks if the date of birth is too far in the past. Is there a minimum date we should validate?

**Comment by stacylorraineprendeville** [comment]
@aprojas Incorrect data due to incorrect entering of the data is never going to be avoidable ;) We can fix to 1910 as the oldest @javierpf

**Comment by javierpf** [comment]
Thanks! I'll also add validation for the oldest date then!

**Comment by javierpf** [comment]
Now, the date picker won't allow you to select a date before 01-01-1910
