### ISSUE TITLE
Review not authorized screen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#301]
Review the design of not authorized screen/session has expired screen

**Comment by stacylorraineprendeville** [comment]
@javierpf Can you give me all instances 
Session expired means that all data is lost?

**Comment by javierpf** [comment]
@stacylorraineprendeville I'm not so sure if we need this screen. Right now, if the user is unauthorized, it redirects to the login page, which is probably fine and we don't need a specific UI for this.
About your question, the user can be unauthorized if:
* There's no session token in the URL nor the localStorage.
* The session token expired.
If the session expires, we lose the draft.
