### ISSUE TITLE
Indicators definitions for "i" icon

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#306]
Collect the indicators definitions of ALL surveys with @aprojas for the "i" icon.

**Comment by stacylorraineprendeville** [comment]
@aprojas shall we revive this now that we have the capacity...

**Comment by aprojas** [comment]
I will add this per issue 

@stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@aprojas OK - So if you are going to make seperate issues for these then we can close this
