### ISSUE TITLE
Progress bar is missing

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#308]
The progress bar is missing in the whole lifemap.

**Comment by stacylorraineprendeville** [comment]
@javierpf I am assigning this to next sprint as we are surely tight on time for this

**Comment by javierpf** [comment]
@gonzarodriguezt I've added some comments in the PR. Please review the current implementation according to​ those comments.

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt @javierpf POssible to push this with the launch?

**Comment by javierpf** [comment]
@stacylorraineprendeville yes, we agreed on some improvements with Gonza for the last couple of days, that's why this is not merged yet. I'll review it again as soon as I can!
