### ISSUE TITLE
Missing sticky popup of priorities in the lifemap page

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#310]
The sticky popup is missing in the lifemap page. The "don't forget to add priorities" popup. 
This appears when it is mandatory to create priorities, but it should always appear, mandatory or not.

**Comment by stacylorraineprendeville** [comment]
Still seeing this screen when I click on the continue button without completing the required priorities![Screen Shot 2019-05-10 at 20.21.27.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/96f5d34d-d06c-4bdd-8268-446c18e8c09b)
