### ISSUE TITLE
Add title "Now just click save" in the final part

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#320]
In the final screen of the lifemap, add the title "Now, just click save!" after "Your lifemap is completed!" 
Please confirm this @stacylorraineprendeville

**Comment by aprojas** [comment]
I cannot see this @javierpf

**Comment by stacylorraineprendeville** [comment]
@javierpf Moving this back into progress as just check on demo and this is not compelted.
