### ISSUE TITLE
Some indicators should no be skipped

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#327]
Certain stoplight questions should no be skipped. Currently every question it's mandatory but  it's possible to skip them. 

* Expected *
An extra column in the table survey_stoplight to tell if an indicator can be skipped or not and to pass that information to the front end

**Comment by stacylorraineprendeville** [comment]
? @JDelPuerto Have you also created a task for the mobile app? Or just here in the stoplight web?

**Comment by stacylorraineprendeville** [comment]
Issue moved to [FundacionParaguaya/FP-PSP-SERVER #663](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/663) via [**ZenHub**](https://www.zenhub.com/)
