### ISSUE TITLE
Teaser Text on Survey Page

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#337]
On the Surveys page where it states...
Short description that can go over two lines...

Can this be fed the real text?

**Comment by gonzarodriguezt** [comment]
Yes! I just checked and we can, we also have the createdAt date field.

**Comment by gonzarodriguezt** [comment]
@stacylorraineprendeville 

This is how it looks with two lines, in some Surveys the important part of the description doesn’t show.

<img width="1045" alt="Screen Shot 2019-05-09 at 17 57 40" src="https://user-images.githubusercontent.com/13141462/57539450-89cf8a00-7318-11e9-9109-3f8129486496.png">

This is how it looks with three lines, the height increments dynamically as the description grows.

<img width="1009" alt="Screen Shot 2019-05-09 at 18 59 36" src="https://user-images.githubusercontent.com/13141462/57539503-a2d83b00-7318-11e9-97a1-cdd3eec9dbf8.png">
