### ISSUE TITLE
Internationalisation in Date picker

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#341]
When viewing the date picker in english 
The week day is presented in Spanish.

![Screen Shot 2019-05-09 at 16.54.13.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/2b67b7ff-b6f8-4cc7-9e99-6cbcdbca1d63)

**Comment by javierpf** [comment]
@stacylorraineprendeville I've tried several times and could not reproduce the issue. Can you please confirm this is still an issue and provide steps to reproduce it if it is

**Comment by javierpf** [comment]
@stacylorraineprendeville this is the list of updates in terms of date formatting: 
* Improved Spanish localization (removed periods, capitalizing words).
* Using this format for Spanish: "D [de] MMMM, YYYY", that will end up displaying: 13 de Mayo, 2019.
* Using this format for English: "MMMM D, YYYY", that will end up displaying: May 13, 2019
