### ISSUE TITLE
UX - Fill out mandatory Field message is a bit strong.

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#342]
![Screen Shot 2019-05-09 at 17.06.09.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/137d90ea-16ab-4266-84da-cb1ec2c2df16)[Uploading... Screen Shot 2019-05-09 at 17.06.09.png ]

**Comment by javierpf** [comment]
After chatting about this with @stacylorraineprendeville, we'll improve form error notification  by:
* Scrolling to top.
* Displaying a snackbar with message `You have ${number} of fields that needs the content checking`.
This should be added in Primary Participant, Family member and Economic questions.

**Comment by aprojas** [comment]
Hi @javierpf Do I just have to test if the message appears?

**Comment by javierpf** [comment]
@aprojas Instead of the error modal window that used to appear (see screenshot above), you should see a small snackbar at the bottom containing the number of errors in the page, and the whole page should scroll to the top.
