### ISSUE TITLE
Parts of the title not showing on Title Bar

### ISSUE THREAD

**Issue by grdnrt** [FundacionParaguaya/stoplight-web#347]
This happens when the title of the question is too large. Specifically on the Geco survey.

![Screen Shot 2019-05-09 at 17.15.58.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/26167dd0-8f9c-4bc9-b339-70152960cf56)

**Comment by stacylorraineprendeville** [comment]
We are speaking with the client regarding this.
