### ISSUE TITLE
Date format not correct on Survey Page

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#348]
On the Created On field, it should be like: May 09, 1988.

**Comment by stacylorraineprendeville** [comment]
Strange full stop has appeared![Screen Shot 2019-05-10 at 19.53.23.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e20ea55d-60e8-4010-83af-8acaeef81530)
