### ISSUE TITLE
Add a "Your lifemap is saved" message - Nice to have for launch

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#350]
When a user clicks on  "Save and Close"

Should we add another modal pop up - 

"Your life map has been successfully saved"

**Comment by aprojas** [comment]
I cannot see this. I just finished a WARC survey and did not see this pop up.
@javierpf

**Comment by aprojas** [comment]
Hello! I still cannot see this! @javierpf

**Comment by aprojas** [comment]
@javierpf  
This already shows! BUT I think it should be "lifemap" with no space in the middle. Sorry if I wasn't clear on that. 
@stacylorraineprendeville can confirm this?
