### ISSUE TITLE
UI Issues in Material Design with two lines in form element

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#353]
![Screen Shot 2019-05-09 at 18.01.49.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e3ad91be-e3c5-49d8-acd8-4291edff51c1)

**Comment by stacylorraineprendeville** [comment]
creo que sigue en los mensajes de "error" - cierto?
![Screen Shot 2019-05-13 at 16.52.00.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ee44214f-c0b2-4602-b66a-db322a7a7b3a)

**Comment by gonzarodriguezt** [comment]
Fixed!
