### ISSUE TITLE
Final Screen - Print functionality

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#357]
When the user clicks on the 'Print' button, the user should be prompted a browser print form for printing the Final Screen page

**Comment by stacylorraineprendeville** [comment]
hmmmm - not seeing the screen with the lifemap indicators here![Screen Shot 2019-05-10 at 20.26.03.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/8a5f38a4-a09d-49eb-8672-c554a5b5b43a)
