### ISSUE TITLE
Date Format retrospectively in Date field

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#360]
![Screen Shot 2019-05-10 at 19.45.24.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/cd02ae79-fda9-4360-b443-b37303e74e94)

![Screen Shot 2019-05-10 at 19.47.16.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/1dd7d1e8-e589-49c1-8c46-a92fd64d9fa1)

Please revert to 
Mayo 9, 2019
May 9, 2019

For consistency

**Comment by javierpf** [comment]
We have decided to keep those formats, as the English format can be weird for Spanish speakers
