### ISSUE TITLE
Dashboard Redesign

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#363]
This epic is for the creation of the dashboard re-design in line with the design at:

https://projects.invisionapp.com/d/main#/console/16366206/362799620/preview

The below is an approximation - The design is evolving during this time. Issues are created for completed blocks only.

The first release for this will need to have something to show to clients during the last week of July.

This is the latest version of the design

![Screen Shot 2019-07-03 at 12.33.26.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/27a61034-4e7c-46f7-986d-ee0e44deb539)

**Comment by gonzarodriguezt** [comment]
🎉

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt Si! Well done!
