### ISSUE TITLE
Create Overview Block

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#366]
![Screen Shot 2019-05-11 at 13.19.23.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/7bb5f5c1-71a8-4ace-9854-7efc89c6dedc)

**Comment by aprojas** [comment]
This should only appear in the Analytics section right?
@gonzarodriguezt

**Comment by stacylorraineprendeville** [comment]
@aprojas no - this is for the new dashbaord

**Comment by aprojas** [comment]
@stacylorraineprendeville So I will see it logged in as a hub or org or mentor?

**Comment by gonzarodriguezt** [comment]
Yes! So at the time you can see and test it in `/analytics`, but actually it is for the Dashboard, the things is that the Dashboard screen isn't created yet. @aprojas

**Comment by aprojas** [comment]
Thank you!! @gonzarodriguezt

**Comment by aprojas** [comment]
Added this new ticket before closing this one:
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/stoplight-web/508
