### ISSUE TITLE
Create Operations Chart

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#367]
Please note link to operations will NOT be relevant in step one
![Screen Shot 2019-05-11 at 13.21.02.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ea8c00fb-952f-485c-940b-013dff6ada6d)

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If the operation chart is created and visually correct

*How to Test*:
Go to `/dashboard/` as a demo user,
