### ISSUE TITLE
Create Operations : Activity Feed

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#368]
Please note - The Inline Scroll appears on ROLLOVER OF THE AREA

We can set a maximum number of 25 until we have the operations section functioning.
On Rollover  -See Effect in Inivision
On Click - URL Link to the family lifemap

![Screen Shot 2019-05-11 at 13.22.52.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/73d1d814-31bf-4ed5-b745-c9ffd8c90336)

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If the activity feed is there and visually correct

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there
