### ISSUE TITLE
Create Date filters for new dashbaord design

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#369]
![Screen Shot 2019-05-11 at 13.49.16.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/6f8f05e8-2f0e-44c6-97e4-476edf1512b8)

**Comment by javierpf** [comment]
@stacylorraineprendeville Should this work with a Date Picker?
I thought we were going to plan a new way of picking dates, maybe through 3 different input fields (day - month - year)?

**Comment by stacylorraineprendeville** [comment]
@javierpf I tihnk the date picker we have is terrible for Birth dates - However for report dates it is not so bad. -We can look at other options and in the interim just use what we have - correct?

**Comment by stacylorraineprendeville** [comment]
@javierpf can you groom this with the date picker we have currently

**Comment by stacylorraineprendeville** [comment]
@javierpf need grooming
