### ISSUE TITLE
Create Organisation Filters 

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#370]
![Screen Shot 2019-05-11 at 13.51.12.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e0c49bdb-81be-4a8f-82f2-76d28e4bd017)![Screen Shot 2019-05-11 at 13.51.20.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c725dd1a-710b-4d54-b45d-5c16a30a2734)

**Comment by javierpf** [comment]
As per @loorely the backend functionality for this issue is already available.
