### ISSUE TITLE
Create overall page design elements

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#371]
Create header elements and navigation as well as overall page structure.

![Screen Shot 2019-05-11 at 13.53.02.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e0a215d8-ba53-4e5a-8bec-621e95b7ae79)

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If the dashboard works and it looks like the design on this ticket

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there
