### ISSUE TITLE
Creating priorities

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#377]
When priorities are NOT mandatory - The following message appears currently (see below):
This should be

To complete the life map...
Create priorities!

![Screen Shot 2019-05-13 at 13.53.06.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ca1d0acb-2c18-4892-838d-ea22ed373b9c)

**Comment by stacylorraineprendeville** [comment]
Just reviewed this and I am still receiving the same erroneous message - that I created all my priorities when in fact I did not create one!


![Screen Shot 2019-06-11 at 10.47.44.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/9abb0c62-d35c-4980-be4e-acfaa78915ce)

**Comment by javierpf** [comment]
@stacylorraineprendeville Currently, @aprojas is testing using the current developing version. What you see in DEMO is basically the current 'stable' release `1.0.0`. So, this should be tested in development, @aprojas has access to the instance now
