### ISSUE TITLE
Remove "future"years in the date picker

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#378]
Remove future fields for date of birth fields

![Screen Shot 2019-05-13 at 14.16.25.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/57b4fabc-53f4-4f09-a1b5-8e5a4d5f25a8)

**Comment by javierpf** [comment]
@stacylorraineprendeville I think we should first decide if we're keeping the date picker we have now, or build a new one. If we go with the second option, probably it's better not to waste time upgrading the current picker
