### ISSUE TITLE
Improvements to Print Screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#379]
Currently the print download bleeds into the two pages....
This task is to resolve this issue on print.
[https://app.zenhub.com/files/161184202/9fddb530-0cc1-4ac2-8127-24761eed7141/download]

**Comment by aprojas** [comment]
The comments from partners is that before, the printed lifemap was in one whole page. Now it's set in  more than 1 page. 

We need the lifemap to be printable in only one whole page.
Also, the priorities and achievements should be in the printed version, on a second page.

**Comment by stacylorraineprendeville** [comment]
@aprojas How do we fit 52 balls and all the text in one A4 document? Was this really happening or do clients just say it? Becuase I never had a 1 page print!

**Comment by aprojas** [comment]
I'll create another issue for the priorities. 

This was how the print screen looked before. @stacylorraineprendeville 

![....png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/07de0201-a80d-45b5-8e83-927e3c8da225)

It may not be pretty visually, but it was what we offered before.

**Comment by stacylorraineprendeville** [comment]
We will close this as not worth it while we create a new report
