### ISSUE TITLE
Beta badge on Header

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#385]
<img width="331" alt="Screen Shot 2019-05-13 at 17 31 53" src="https://user-images.githubusercontent.com/13141462/57658481-12feef00-75ad-11e9-8c7f-1a972b910124.png">

**Comment by aprojas** [comment]
Don't we have to remove this badge already?
@gonzarodriguezt

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt @aprojas the beta tag will be page per page - so yes we can remove this from here as it is in production
