### ISSUE TITLE
Fix Header of the Life Map on Responsive Version

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#390]
<img width="427" alt="Screen Shot 2019-05-17 at 14 35 26" src="https://user-images.githubusercontent.com/13141462/57949077-5f9a4100-78b1-11e9-88b5-e8cf41b61b07.png">

It should be centered and re-sized

**Comment by aprojas** [comment]
Is there a way to review this? @gonzarodriguezt

**Comment by aprojas** [comment]
I tested this and these were the results:

1. Headers are not properly aligned
![fdgfhjg.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/0ecd7081-2847-4ea5-8d55-6fe6ddf9542a)

![erte.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e4311a0c-71bf-49e6-a284-4216eb8a69ac)

2. The indicator titles of the final screen do not fit properly.

![errte.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/27e48ab6-96dd-4a83-b6d3-e22d53fc8c22)

**Comment by aprojas** [comment]
How do we continue with this? @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
I think we can create a ticket for the responsiveness of the platform, there are to many screens to be addressed @aprojas

**Comment by aprojas** [comment]
Ok great. Can you create it? Since you understand the specs of it @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
Fair enough, i'll created it @aprojas
