### ISSUE TITLE
Google chrome translation error

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#391]
Incorrect texts appear in some indicators in ACTIVATE survey, and in some dropdown options. 
Refer to: "nariz" dropdown option explained by Stacy. 

This happens when a user uses Google chrome browser with the translator activated.

For example, the text of indicator 2 was correct in mine, but it wasn't in my colleague's.

I can upload some pictures when they send it to me.

**Comment by stacylorraineprendeville** [comment]
@javierpf I forgot about this strange bug ;)
We can talk about it after a standup and I explain what it is....

**Comment by stacylorraineprendeville** [comment]
We found that this happens when a user has Google Translator installed
even when the page is in spanish it tried to convert the text into spanish -thus the error
It seems that page language is not defined

**Comment by stacylorraineprendeville** [comment]
hmmm - the plot thickens see
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/stoplight-web/428

So first thing is this issue in that if I am viewing in Spanish I do not want Google Translate to translate to spanish ;) This is the first task to look into and satisifes this issue.

But secondly the wider issue is that we do NOT have mulitlingual capacities - We do not translate socio economic. Do we need to? If we had a proper user account system we could fix the language per user? These comments are just for a wider chat.

**Comment by javierpf** [comment]
@aprojas @stacylorraineprendeville can I have more information about the "nariz" dropdown option? How can I reproduce that using a Survey available in testing env?

**Comment by aprojas** [comment]
The person using this survey had the Google Chrome translator activated.
So, when taking the survey ACTIVATE, which is in SPANISH.
The translator thought that it had to translate from English. 
However, the survey was already in Spanish. 
And the Translator translated the option "no se", to "Nariz" because it looks similar. But actually, it's just "I don't know" in Spanish. 
@javierpf

**Comment by javierpf** [comment]
Ok, so this only happened because the user had the automatic translator turned on. Is this something to be considered @stacylorraineprendeville? Probably, users with such configuration within their browsers may face this kind of unexpected behavior in any website.
As a workaround, we may use something like this: https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome

**Comment by stacylorraineprendeville** [comment]
WON¨T DO
