### ISSUE TITLE
Economics screens - Support checkboxes and radiobuttons

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#400]
Currently, we support the answerType can be either 'select' or 'string'.
Add support for answerType 'radio' and 'checkbox'. Render the input component according to those values.

**Comment by aprojas** [comment]
This is how I view it @javierpf 
![bug 1](https://user-images.githubusercontent.com/44477708/59464079-820e7400-8df5-11e9-8505-295ee40f7c39.PNG)

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt @javierpf do we need to review the design again? or is this just a test for functionality

**Comment by aprojas** [comment]
I cannot close this yet until #773 is solved. 
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/773
