### ISSUE TITLE
Incorrect message when finishing a survey + adding priorities

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#403]
I finished a Paraguayan survey and the message "Great! You created all the required priorities" appeared , and I have just finished the indicators part, I did not create any priorities. 

![2019-05-16 (5).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/aa49921d-dc65-44fa-9f10-9e84a46c0cd3)

**Comment by stacylorraineprendeville** [comment]
@aprojas Pretty sure we alrady have a ticket for this and it has been worked on
@javierpf do you want to confirm :9

**Comment by javierpf** [comment]
Will deploy the new version asap.

**Comment by stacylorraineprendeville** [comment]
OK closing as this issue is already rectified.

**Comment by stacylorraineprendeville** [comment]
@aprojas can you confirm this is completed

**Comment by aprojas** [comment]
No, this is still happening! I just took a survey in demo environment and the message still appears even though I have not made any priorities yet. 

@stacylorraineprendeville @javierpf

**Comment by stacylorraineprendeville** [comment]
@aprojas pretty sure this ticket is a duplicate - can you research and if so close this with reference to the other ticket

**Comment by aprojas** [comment]
Yes it's a duplicate of #377 
I'll close it @stacylorraineprendeville
