### ISSUE TITLE
GIT HUB Vulnerability

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#413]
Please investigate

![Screen Shot 2019-06-06 at 12.05.57.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/05de7d36-c8dc-43f4-816a-2f9e63ec9237)

**Comment by gonzarodriguezt** [comment]
This is a new feature GitHub added recently i think, but it's about the version of the tools we use, i also was scare when i saw those in my personal repos

**Comment by javierpf** [comment]
@stacylorraineprendeville this is actually for the stoplight-server, project that as far as I know, is not being used.
@diegotorrespy @pA1nD can you please share your comments about this project? Should we keep updating it or is it, in fact, not going to be used anymore?

**Comment by stacylorraineprendeville** [comment]
Guys - please answer
@diegotorrespy @pA1nD can you please share your comments about this project? Should we keep updating it or is it, in fact, not going to be used anymore?

**Comment by diegotorrespy** [comment]
@javierpf @stacylorraineprendeville @pA1nD 
As long as I know, this node project is not used anymore by the website so we can move these files to another repo as a backup and delete them from the server repo.

**Comment by pA1nD** [comment]
Diego, you made the last commit to this repo. So do you know what is the functionality that you were using it for?

It might be important for some sync between ETL and PSP.

BTW: I checked the vulnerability and it's unlikely that we're exposed to a risk. But I think it would be great to delete it if it's not doing anything anymore. Will also talk to bryan.

**Comment by pA1nD** [comment]
Results from checking:

(1) Used to be the "new server". This part is not relevant any further and can be deleted.
(2) No functionality for ETL connection.
(3) Repo used to contain scripts to sync B -> A. As far as I know did Diego reimplement this in another way. @diegotorrespy correct? And might not be needed going further.
(4) Contained scripts to reset testing and demo. But seems like those are not relevant anymore as well? @javierpf what's the state there?

==> If all of the above points are not in use anymore, we could archive this repo.

**Comment by diegotorrespy** [comment]
@pA1nD @javierpf 
Great, thanks so much Bjorn,

Regarding point 3. Correct, I have already migrated this logic into the back end project.
Regarding point 4. We have disabled the automated reset of the databases and including the migration by environments through Liquibase.

**Comment by stacylorraineprendeville** [comment]
@javierpf shall we archive this - and close this -
