### ISSUE TITLE
Priorities and Achievements in Print screen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#416]
The priorities and achievements, stated by the participant who takes the survey, should be displayed in another sheet for the print option. After the indicators.

**Comment by aprojas** [comment]
Can we close this since the priorities are being shown in the print screen?
the achievements are not shown but this was not asked for. 

@stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@aprojas the idea was to link this more effectively with the families pages and have a report on screen of the priorities- Now it does not seem worth doing - I will ice this

**Comment by aprojas** [comment]
This is done!
