### ISSUE TITLE
Change description of UK's survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#417]
The UK does not want the word "poverty" in their survey. 
Please change this box description to "The U.K. version of the Stoplight - 2018". 
This has to be changed in both demo and production environments.

**Comment by stacylorraineprendeville** [comment]
@aprojas please specify where this text is - Not clear in this issue.

**Comment by aprojas** [comment]
@stacylorraineprendeville I cannot upload the screenshot since it's too big. 
 
It's called the "description of the survey", when you log in as a survey user, you need to click on your survey to take one, it has the shape of a square. And in that square, the text now says
"UK version of the Poverty Stoplight- 2018"
We have to take the word "poverty" out.

**Comment by gonzarodriguezt** [comment]
I think this is for the backend team, as they can make changes on the details of each survey @diegotorrespy @JDelPuerto

**Comment by JDelPuerto** [comment]
It's ready for testing @aprojas in the testing env.

**Comment by aprojas** [comment]
This is ready to move to production please!! 
@JDelPuerto Thank you!

**Comment by aprojas** [comment]
This will also be changed in the demo environment right? @JDelPuerto

**Comment by JDelPuerto** [comment]
We can deploy in  Demo as well @aprojas

**Comment by aprojas** [comment]
Great! Let me know when it's in production too please. @JDelPuerto
