### ISSUE TITLE
Long indicator titles don't fit properly

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#418]
I was taking the GECO survey in the demo environment, and the long titles appeared like this:

![Imagen de iOS (1).jpg](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e116c378-1b89-49c4-835f-3819772bc1ca)

They do not fit properly in two lines, and the user is not able to read all of it.

**Comment by stacylorraineprendeville** [comment]
@aprojas what is the length of this title - We were tld by Kathy we had a 60 character length - this looks longer - Can you confirm?

**Comment by aprojas** [comment]
@stacylorraineprendeville 
Yes, I see this is longer than 60 characters.
