### ISSUE TITLE
Printing, Emailing & Downloading the Stoplight

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#419]
As a user
I want to print my poverty stoplight 
with page 1 including all the indicators (we are revising if this is possible space wise!) on an A4 sheet
and page 2 including the priorities
so that I can keep this for future reference.

As a user I want to email this printed version directly to me.
As a user I want to be able to download this document to my desktop.

Wireframes as an idea of what we want:

[https://app.zenhub.com/files/161184202/d3f163d0-17d8-43ef-9977-b41754477e52/download](https://app.zenhub.com/files/161184202/d3f163d0-17d8-43ef-9977-b41754477e52/download)

[https://app.zenhub.com/files/161184202/5dc6ca15-3fcc-4bc6-939e-5156df4ebf00/download](https://app.zenhub.com/files/161184202/5dc6ca15-3fcc-4bc6-939e-5156df4ebf00/download)

**Comment by javierpf** [comment]
@stacylorraineprendeville @diegotorrespy emailing should be handled by the backend.
Current implementation covers printing functionality.

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy can you flesh this out and create an issue with Gaby - Also can you add Gaby to our GIT HUB - I do not have her as part of the team and cannot add her here in a tag.

@javierpf The downloading option? - Also once we have the new issue from Diego and Gaby can you revise the title of this issue

**Comment by aprojas** [comment]
Just wanted to remind that the print view should be horizontal. Now I see it vertical. 
@javierpf

**Comment by stacylorraineprendeville** [comment]
@javierpf Also I have one change from Eduardo
Instead of the title "My Life Map"
It should say Gustale’s Lifemap....

I am not so sure about the ´s being universal and I do not have time now to review it
Could it be

Stacy Prendeville, Life Map

i.e. can you add a name print - (this can be a seperate issue next sprint if you need)

**Comment by javierpf** [comment]
@aprojas this should be horizontal? Sorry I've missed that. This applies for both indicators and priorities pages @stacylorraineprendeville ?

**Comment by stacylorraineprendeville** [comment]
@javierpf yes for both pages - horizontal :)

regarding the download button - Please only add these to the last screen and just leave them on one line -It does not matter that there are only two
 ![Screen Shot 2019-06-19 at 10.24.18.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5603ccad-98f8-433d-b5c8-6d6a846030ec)

**Comment by javierpf** [comment]
Got it! I'll make those changes. Moving back to In Progress

**Comment by aprojas** [comment]
I checked that the print and download options work perfectly!!

@javierpf @stacylorraineprendeville 

Can I close it? The emailing option we can move to another ticket.

**Comment by javierpf** [comment]
@aprojas I've created another ticket for the emailing functionality, so if Print and Download functionalities have been QA'd, you can close the ticket.
