### ISSUE TITLE
Amends to lifemap results screens

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#422]
** Currently the lifemap results page looks like this:** 

![Screen Shot 2019-06-10 at 13.28.04.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/67b1800e-a10c-48bd-a7c8-6cdfbb436490)

One client has complained regarding this and has been told it will be changed! 

** The resolution then is to ** 
- Remove the PIE CHART and the lifemap visualisation below it.
- Remove the Dimensions (Header and Line chart)
- Utilise the responsive width.

** See image below: ** 
![Screen Shot 2019-06-11 at 11.04.26.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/86ba6e60-004b-45d7-bae5-c9a05d26917f)

** What I mean by "utilising the responsive" **
I notice in the larger width currently we simply increase column spacing.

![Screen Shot 2019-06-11 at 11.05.32.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/9892cab8-24e2-4732-834e-4c5c748fd269)

** So the idea would be to add further columns when responsive gives is this width.**
as below

![Screen Shot 2019-06-11 at 11.07.02.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/49b8354b-5535-4bdd-83d0-04912664e3bc)

** Please can we review the final design together** - Perhaps we can also save further space by changing slightly padding and text size - Let´s test this live

** On the results page (the final screen) **
We must also remove the pie chart.
Apparently pie charts are not for lifemaps as part of the methodology (!)
So here again we remove the pie chart.
Can we ensure here that the lifemap visualisation DOES retain a smaller width and does NOT use responsive features - Expalined below

** Currently we see this:**
![Screen Shot 2019-06-11 at 11.16.01.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5d87d673-58e4-419d-96ae-cebfd733053b)

** Desired Result **
![Screen Shot 2019-06-11 at 11.34.13.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/19ad20a6-3e79-4f73-835a-8b5938c9c485)

**Comment by gonzarodriguezt** [comment]
Currently we have the progress bar on both Overview and Final screen, but i don't see it in this images, we should remove it?

**Comment by gonzarodriguezt** [comment]
We can handle one more breakpoint at > 1920px, with 12 columns, is this okay @stacylorraineprendeville 

![Screen Shot 2019-06-12 at 13.46.51.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/3676260e-920d-40cd-b823-cb9f88fa8591)
