### ISSUE TITLE
Analytics "Beta" - Dimensions and Indicators Visualisation

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#424]
As a HUB User
I want to see the visualisations per dimensions
and the indicators
so that I can see progress from the poverty stoplight AND use these images in my visualisations.

This issue is simply to take advantage of the work we have completed and preview it to clients asap.
The idea is to open the "analytics" section in beta.
The visualisation below is two visualisations already created.
The idea is to create the page - It does not matter if we do not have PIE chart views, or priorities.
More important to give the dimensions and indicators views to one of our clients who has been asking for these over many months.
With this particular client I will have a meeting on the 18th morning european time. Would be great if this could be visible - If not in production then if you could simply give me an online link even without real data just to show her this working for the meeting.
Let me know

![Screen Shot 2019-06-11 at 12.04.34.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c78e9d17-2185-4673-9e1e-e48ccb59894c)

**Comment by stacylorraineprendeville** [comment]
@javierpf @gonzarodriguezt as per the description of the issue - I have a client meeting on the 18th - now tomorrow
Do we have something I can show - My meeting with this client is straight after the stand-up tomorrow? I need something -even if it is just a URL without the work being connected to the platform.....

**Comment by javierpf** [comment]
@stacylorraineprendeville current work in progress can be reviewed using the testing instance: https://ps-sw-testing.netlify.com/surveys?sid=2502277a-5b27-452e-ac65-9a0d7fbd8d97&lang=en&env=testing

**Comment by stacylorraineprendeville** [comment]
Brilliant!

Remember we will need that Beta tag by the page title as it will be visible to hubs and organisation

Can you add “alt” text to all the elements - Priorities/Achievements/Pie Chart/List View/ etc

Also the dimensions text is this really the right size? I would make this a little larger and the dimensions text a little smaller so these are the same size for visual coherency

And for the indicators can we add a small area to explain the statistics

**Comment by gonzarodriguezt** [comment]
The small area of indicators is referring to a paragraph below the title? Or some explanation for each indicator maybe? @stacylorraineprendeville 

And also, i ended up creating tickets for the comments that i considered were a feature, for the others, that are related to this ticket, i will just do them in this ticket.

**Comment by stacylorraineprendeville** [comment]
This little pop outs should be available on charts - kind of like high charts
https://www.highcharts.com/demo/line-ajax
make sense?

**Comment by gonzarodriguezt** [comment]
Makes sense! Reference #449 @stacylorraineprendeville
