### ISSUE TITLE
Internationalisation is NOT working with language changer

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#428]
Here we have an issue in that we DO allow users to change the language - HOWEVER surveys are mot mulitlingual - So we can say
Choose English Language
Open Activate Paraguay Survey
Begin survey
Form fields will be in English in the family members pages - as will headers 
Dropdown content is in Spanish and the socio economic questions are NOT translated.
![Screen Shot 2019-06-11 at 10.27.38.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/4e93b1bf-fef4-4c17-b7fd-838fe6792267)

Desired results
Either we translate ALL surveys into the two languages OR we accept that certain surveys are ONLY available to certain languages.

Lets think about this.

**Comment by stacylorraineprendeville** [comment]
Should users simply choose the language in a profile page? Would this resolve this issue?

**Comment by javierpf** [comment]
@stacylorraineprendeville this happens because all dropdown options obtained from the backend are defined in 1 specific language, so both apps (web and mobile) cannot translate them. That's why all other labels are correctly translated but the options aren't.
