### ISSUE TITLE
Resume Draft in the Life Map Online

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#431]
As a mentor user
I WANT TO 
save a draft
SO THAT I CAN
take the survey over multiple sessions because it is long!

** This is coming in as urgent for ONE client. We gave a prospective date of Jul 5 **

** How will it work ? **

As per the App - On clicking "x" instead of the message that you will loose all work your work will now automatically be saved as a draft AS LONG AS you have filled out the family member name of the participant page (we cannot save drafts with no name). 

![Screen Shot 2019-06-17 at 14.24.29.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/5ff04a7e-084e-4f92-a460-36d76ef9aafc)

If a user has NOT filled out any details of the participant the draft cannot be saved (This would happen on Terms/privacy pages or the participant page with no first name, last name)

![Screen Shot 2019-06-17 at 14.31.40.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/05ed7cd6-1c3c-44dd-8d3b-4090934bbdec)

On the Surveys Page (strangely enough the mentor login has no dashboard currently) we will create a list of all DRAFTS.

![Screen Shot 2019-06-13 at 13.51.55.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e66f19c2-6f6b-420e-950f-01b46b86e074)

Clicking on the draft should take you to the page which you left the process.
Drafts will not be accessible direct from a Family screen - only from the surveys page- because of longer implementation timings. This will need to be explained to the client (Stacy).

-------------------

We can further groom next week with a UI-......You can turn this into an EPIC if required to group a number of tasks.

**Comment by stacylorraineprendeville** [comment]
@javierpf You asked if there would be changes to this page in the future - yes - A rough idea would be this below - This is very ROUGH (again created in  few hours) but this is a general direction of where we could go - The spec above is what we need for July 5 - To my mind we can expand to the image below later and it would save the time needed in the next sprint to just get the functionality up and running................Your thoughts...

![Screen Shot 2019-06-17 at 14.06.36.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/2e96d65b-ed15-4830-870b-a551dfa99f0d)

**Comment by javierpf** [comment]
@stacylorraineprendeville This looks nice, and it covers the possibility of having more than 1 survey available on the right side (even though we don't have such case right now).
Also, the table at the bottom will be used for both retaking life map and resuming draft functionality, right?

**Comment by stacylorraineprendeville** [comment]
@javierpf the retaking is dealt with via going to a family page and retaking OR creating a new survey and selecting an existing family.
Right now the list is all surveys whether in draft or completed state (regardless of whether you want to take these again)
