### ISSUE TITLE
Editorial amendments to lifemap online

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#436]
2. It should be "Life Map". This is in the screen after clicking on "Save and close". AND should have a period at the end of the sentence.
![lifemap2.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e53cc51d-b275-4b7e-819f-70c5ec0ae2c3)
----------------------------------------------------------------------------------------------------

3. There's a white background on each icon. 
![lifemap3.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1d7ca682-6c9c-4e38-96a3-cd87ef5efee8)
----------------------------------------------------------------------------------------------------

4. It should be "Omitir esta pregunta", because it is just a normal sentence, shouldn't be with upper case.
 ![lifemap5.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1ed86bdb-f1c7-4a74-be26-e01891bfbd6e)
----------------------------------------------------------------------------------------------------

5. Warning! should be in Spanish "¡Cuidado!" or "¡Atención!". Don't we use this word in Spanish other places?
![lifemap6.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/75fc4f55-b122-4650-a3aa-b647216d9f83)
----------------------------------------------------------------------------------------------------

6. It should say "Mapa de Vida" and this sentence should have a period at the end. 
![lifemap7.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/95a1d518-8bdd-427a-bcae-c91cf2269929)
----------------------------------------------------------------------------------------------------

7. As similar to number 4, this should not be upper case. JUST "Skip this question"
![lifemap8.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ddaae026-72b5-4791-98a0-4000be71db8d)

**Comment by stacylorraineprendeville** [comment]
@aprojas editorial team need to confirm but previously it was stated this was Life Map capitalised
I sent a message to Kathi to confirm this

**Comment by aprojas** [comment]
Yes! It is "Life Map" and "Mapa de Vida", I will change the description.

@stacylorraineprendeville

**Comment by aprojas** [comment]
All of these are done.
