### ISSUE TITLE
Strange characters when taking a survey

### ISSUE THREAD

**Issue by diegotorrespy** [FundacionParaguaya/stoplight-web#437]
**Description**

At this moment, when a new lifemap is created in the web app, the request is going without the encoding system and sometimes the data contains accents and special characters like `ñ` that are being saved badly in the server.

**To Reproduce**
1. Create the a lifemap that contains accents or special characters like `ñ` with the stoplight online.
2. Search for the created lifemap in the web platform, in the reports for example.
3. See the texts.

**Screenshots**
![special-characters-issue](https://user-images.githubusercontent.com/645391/59463174-5ab6a780-8df3-11e9-9340-7d02296b198a.png)

**Additional context**
This issue was solved in the previous version of the lifemap online in the issue: https://github.com/FundacionParaguaya/fp-psp-frontend/issues/343, related to the encoding format in the front end.

**Comment by stacylorraineprendeville** [comment]
duplicated in https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/mentorapp/784

**Comment by aprojas** [comment]
This works perfectly when I take a new survey in testing.
@javierpf @diegotorrespy 
However, other families that have already been present in the platform still show the special characters incorrectly.
