### ISSUE TITLE
Indicator Definitions

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#439]
@stacylorraineprendeville commented on [Fri Jun 14 2019](https://github.com/FundacionParaguaya/MentorApp/issues/789)

As a user
when I am viewing an indicator
** and this indicator has a definition defined in the survey **
when I click on the i icon
I want to see a modal window with the indicator definition text
so that I can read more before answering.

The navigation element: (i con)
<img width="513" alt="Screen Shot 2019-06-14 at 17 26 08" src="https://user-images.githubusercontent.com/45012899/59520320-fa466980-8ec9-11e9-8c7e-681d7421849c.png">

The modal window:
<img width="514" alt="Screen Shot 2019-06-14 at 17 32 12" src="https://user-images.githubusercontent.com/45012899/59520495-5f9a5a80-8eca-11e9-817b-ef548fe1b809.png">

**Comment by aprojas** [comment]
This was done for WARC
