### ISSUE TITLE
Pie Charts view for Dimensions

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#444]
This task is to add the pie charts view for dimensions

![Screen Shot 2019-06-17 at 15.31.42.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/dd871a58-465d-4835-9f8c-880c17af6541)

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If the dimensions section have a Pie Chart view, it works correctly and it looks visually like this design

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there
