### ISSUE TITLE
Add Tooltips to all charts in Analytics

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#449]
@gonzarodriguezt commented on [Tue Jun 18 2019](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/375)

Tooltips should be styled like this:

![Screen Shot 2019-06-18 at 11.36.18.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/3ca1e72c-b545-426e-a327-00891a684424)

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt can you estimate

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If all charts in dashboard have a tooltip on rollover, and their are aesthetically the same as the design

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there
