### ISSUE TITLE
Enhancements in Dimensions Visualisation

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#450]
From #424 

![](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/8d5dccf0-89bb-48d2-a6a8-34f94cc84700)

![](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/dbaee420-037b-446e-ab01-98580cd8b4f0)

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt What is the enhancement here?

**Comment by gonzarodriguezt** [comment]
Making the font sizes matches to the design... it's more like a fix right?

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt hmm- After a standup lts review it together if you want - You can make the changes and we decide - OK? Remind me ;)

**Comment by gonzarodriguezt** [comment]
This really is only about this [comment](https://github.com/FundacionParaguaya/stoplight-web/issues/424#issuecomment-503028132) about the font sizes @stacylorraineprendeville

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If the design of the Dimensions are aesthetically the same as the design shown in this ticket

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there
