### ISSUE TITLE
Whole dropdown option is not visible

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#451]
In the Emprender survey, some dropdown options are long and therefore, I am not able to read all of it. 

![lifemapp1.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/2e9f2fec-2cb4-4056-9016-e1a547157ee9)

![lifemapp.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/0d9747d9-b6e3-4c1c-81c1-ebdfbf6fdfa2)

**Comment by aprojas** [comment]
@javierpf The issue of the first screenshot is solved. 

BUT the second one no. When I choose a long answer, I cannot see it entirely.

![sdfgh.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f2d63115-9ab8-4b22-8812-439f5fc7a5d0)

**Comment by aprojas** [comment]
Can we close this issue and create a new one for the second one? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@aprojas yes - the main priority is completed the second one is not so important but yes let´s have an issue!
