### ISSUE TITLE
BrowserStack Activation process

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#452]
We reached out [BrowserStack](https://www.browserstack.com/), a cross-browser test company, to get the open-source license they are offering.

We successfully got accepted 🎉and there are a few requirements we need to do in order to them provide us the license. Those are:

1. We need to shoutout BS in our website or GitHub project page, with an hyperlink an attached logo.
2. We need to set-up a [badge status](https://www.browserstack.com/automate/status-badges) to our project.

**Comment by stacylorraineprendeville** [comment]
@pA1nD do you have access to the github

**Comment by gonzarodriguezt** [comment]
We can close this, as we already have the response from them @aprojas
