### ISSUE TITLE
Upgrades in Activity feed

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#464]
There is some information missing in the new activity feed component available in the life map online.
Review this with the backend team so we display all required data

**Comment by stacylorraineprendeville** [comment]
@javierpf What information is missing?

**Comment by gonzarodriguezt** [comment]
For the Activity Feed, we are missing `date` and `mentorName`. @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
hmmm _ date is there in the current platform @gonzarodriguezt so how can it be missing?

**Comment by gonzarodriguezt** [comment]
I just looked up and you're right @stacylorraineprendeville, but the date is displayed when entering on a household, and that's another request, a request made individually for each family when entering in that family screen.

But we need the date and the mentor name in the request made for the list of households, on the current platform, this is the request made in `/#families/`.
