### ISSUE TITLE
Fields with MultipleValue key not sending

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#468]
Related to [#733](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/773#issuecomment-504433309) from `FP-PSP-SERVER`.

This is a bug that's causing the checkboxes field not sending.

**Comment by aprojas** [comment]
This is solved right? @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
Yes! @aprojas
