### ISSUE TITLE
Making mandatory optional poverty stoplight questions

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#472]
Birth dates on Family Members are enforced as included questions BUT these are NOT mandatory.

Clients are now creating Conditional Logic based on Ages - In those surveys it would make sense for the Birth dates of additional family members to be mandatory.

Check the backend specification [here](  https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/722) . Right now NO survey  has data  for this but we can add it for testing purposes in Testing Fupa survey

## Additional context
in the front end add an empty string for all fields that are mandatory for default.

**Comment by stacylorraineprendeville** [comment]
@javierpf Where exactly did this end up?
