### ISSUE TITLE
ProgressBar is missing on Firefox

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#480]
The ProgressBar component is not showing correctly on Firefox.

<img width="1396" alt="Screen Shot 2019-06-25 at 10 10 30" src="https://user-images.githubusercontent.com/13141462/60105538-7bef9000-9731-11e9-8dfd-6ac80bd77dc3.png">

**Comment by aprojas** [comment]
I see the progress bar in the Firefox browser in all 3 environments, demo, testing and production.

@gonzarodriguezt
