### ISSUE TITLE
Indicator and dimension in wrong position

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#481]
When making a priority or an achievement, the order of the indicator and the dimension are in the incorrect order. 
It should be first the dimension (smaller size), and then second the indicator (bigger size).

This happened before in the indicators section. 

![Screen Shot 2019-07-04 at 14.17.01.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/4985b926-b4f6-4890-91b8-20e4d4dfb96a)

**Comment by stacylorraineprendeville** [comment]
@aprojas why no pictures? This is hard to understand without them

**Comment by stacylorraineprendeville** [comment]
@aprojas can you review this and see if you can add a screenshot - hard to udnerstand

**Comment by aprojas** [comment]
The screenshot is too big :( @stacylorraineprendeville 

I already explained it to @javierpf , it means that in the header, they should be in the inverted position (but only when making a priority or achievement) It should follow the same style when choosing the indicator levels.

**Comment by stacylorraineprendeville** [comment]
@aprojas please send me the screenshot over email with this number in the title
