### ISSUE TITLE
Warning for Testing, Demo and UAT environments

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#488]
We are having some issues with clients taking snapshots in the Demo environment. 
We need some visual way to let users know they're not using a production instance.

**Comment by stacylorraineprendeville** [comment]
![Screen Shot 2019-07-12 at 13.00.46.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/6b1ed5b1-0f78-4475-acfe-488989465dd6)

@javierpf quick question....I imagine this type of modal on login to the be the quickets implementation - correct? The other option of a banner running throughout the site I imagine as more complicated while we have the older and the newer version

**Comment by javierpf** [comment]
@stacylorraineprendeville even though I've finished this feature of showing the modal as the first screen after the login, @loorely mentioned that after a while, users will probably still forget that they're in the demo environment and would probably start taking surveys anyways.
Do you think that's something we should still worry about? If so, we'll need a different approach design-wise​.

**Comment by stacylorraineprendeville** [comment]
@javierpf The other option we have is a notification pane throughout - However as I had imagined this would take much more time this method seemed the quickest - If you want to add a notification pane into the two designs styles for demo account fine as long as we are not talking double the implementation time
