### ISSUE TITLE
Lifemap: Create BirthDate View

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-web#49]
Create a form to fill in the birth dates of additional family members

* Require a dropdown DatePicker Component
* Should be present for each additional family member
* Should save the birthdates to the redux store

**Comment by stacylorraineprendeville** [comment]
@gigerbytes I cannot review the technical details of this - this will require @pA1nD 

regarding the front end I have created a new ticket here regarding some issues:
https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/stoplight-web/76
