### ISSUE TITLE
Fix bug in radio buttons

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#495]
@JDelPuerto commented on [Wed Jul 03 2019](https://github.com/FundacionParaguaya/MentorApp/issues/862)

The bug  it's present in radio buttons for family members.Data for testing is in Banco Solidario Survey in testing.

**Comment by aprojas** [comment]
Can you explain what I should test exactly? @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
The correct behaviour of radio buttons in family members, a survey with that functionality available to test is Banco Solidario. @aprojas 

Sorry for the late response.
