### ISSUE TITLE
Indicator images not appearing in ROR survey

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#498]
@aprojas commented on [Wed Jul 03 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/821)

In the web and mentor app, the indicator images do not appear in the Roots of Renewal survey. 
In the web it looks like it is charging forever. 
In the mentor app, nothing appears. 
THIS IS IN PRODUCTION

---

@stacylorraineprendeville commented on [Thu Jul 04 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/821#issuecomment-508361979)

@aprojas wrong repository

**Comment by stacylorraineprendeville** [comment]
@aprojas is this still happening? @JDelPuerto are we sure it is not from the backend?

**Comment by JDelPuerto** [comment]
I think this issue was fixed in [this](https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/821) issue of the server. @stacylorraineprendeville  @aprojas

**Comment by gonzarodriguezt** [comment]
Please let us know if this is already solved

**Comment by JDelPuerto** [comment]
It's solved on  your develop branch.

**Comment by aprojas** [comment]
This was solved in this issue https://app.zenhub.com/workspaces/-stoplight-global-5c11ac5d4b5806bc2bfd00bd/issues/fundacionparaguaya/fp-psp-server/828
@stacylorraineprendeville 
@JDelPuerto 
@gonzarodriguezt
