### ISSUE TITLE
HUB Dashboard Filters for ADMIN and PS Team User

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#504]
This task asks for the addition of filters for HUBs on the dashboard.
The organisation filters will be dependant on the HUB selected.
This is only required for the Admin and PS Team User

![Screen Shot 2019-07-18 at 13.45.58.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/df9eb443-1f80-4e6f-8a2e-e544e3fe4d56)

**Comment by aprojas** [comment]
This is not connected to the back end right?
@javierpf

**Comment by javierpf** [comment]
The backend issues related to this ticket are still in progress
