### ISSUE TITLE
Overlapped text of "search family"

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#505]
In the new view of the web version, when you select the field of "search family",  the text then overlaps the rectangle. 

![over.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/381eda10-49d1-4525-b1e9-d017687e37ad)

**Comment by aprojas** [comment]
This only happened with the resume draft option.. Now I cannot see it. 
Should we close it? 
@javierpf @gonzarodriguezt

**Comment by javierpf** [comment]
The resume draft is coming back for the next release, so let's just keep this open
