### ISSUE TITLE
Stretched header in every screen

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#506]
In the new view of the web version, the header with the circles is very stretched out. 
My zoom is 100% 

![aaaaa.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5783abb0-7305-40f5-97a5-2c16dfe79451)

**Comment by gonzarodriguezt** [comment]
In which browser this screenshot was taken? @aprojas

**Comment by aprojas** [comment]
With Chrome! @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
This is still showing like this? I can't reproduce it @aprojas

**Comment by stacylorraineprendeville** [comment]
@aprojas here we have no browser information - so we are loosing time in trying to reproduce this.
please check if this is still present - make sure you hit on F5 to refresh then report back with the bug template format

**Comment by aprojas** [comment]
I left a comment for that @stacylorraineprendeville 

@gonzarodriguezt This is still happening to me.. And I hit F5 too.

**Comment by stacylorraineprendeville** [comment]
@aprojas Chrome version number please - I cannot reproduce this!

**Comment by aprojas** [comment]
Version 74.0.3729.169 @stacylorraineprendeville

**Comment by aprojas** [comment]
I closed all my tabs and tried it again, and now it appears properly!!

@gonzarodriguezt 
@stacylorraineprendeville

**Comment by gonzarodriguezt** [comment]
Thank you! @aprojas
