### ISSUE TITLE
Add % to the overview block

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#508]
The percentage should be included in the pie chart of the overview block

This is the expected overview block design:

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563313966666139613839366461356438336436613064302f37626235663563312d373161382d346163652d39383.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/17abdac8-4960-4f6a-a444-dc581538c29b)

This is what I say when I tested in the web:

![sdfs.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/df9b4fd0-db76-486f-8a67-aff888d796cd)

**Comment by gonzarodriguezt** [comment]
How much digits after the comma we should show? Or maybe just floor/ceil it to the nearest integer? @stacylorraineprendeville @javierpf

 ![Screen Shot 2019-07-08 at 16.07.11.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/b265675c-2786-4474-82d1-1f35d2e68733)

**Comment by stacylorraineprendeville** [comment]
The whole thing must add up to 100 - We should in my mind leave it at 25% otherwise its too complicated - @javierpf

**Comment by javierpf** [comment]
@stacylorraineprendeville @gonzarodriguezt if losing some precision is not a problem, we could make use of the [round]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round) function.

**Comment by stacylorraineprendeville** [comment]
I think for the PIE it is better to just easily add up to 100 and use the round function - knowing the standard of our clients and their current visualisations from excel.
Later I guess we can always change it @javierpf @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
Cool thanks @stacylorraineprendeville @javierpf
