### ISSUE TITLE
Life Map - Editorial revision

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#509]
the correct spelling of Life Map
is

Life Map

with capitalised letters. 
This is confirmed by the Methodology team.
Please ensure this is in place in the front end.

**Comment by gonzarodriguezt** [comment]
This applies also for cases when it's not at the start of a sentence? e.g `Create a life map`. @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt everywhere according to methodology

**Comment by gonzarodriguezt** [comment]
This should be fixed with #511 @aprojas made the last changes there!
