### ISSUE TITLE
Thousand position for Emprender

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#510]
@aprojas commented on [Tue Jul 02 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809)

The following requirements for including thousand position in the Emprender survey:
When writing an income in a specific field, the period in the thousand position should appear.

1. Should be a period in the thousand position (.) 
For example: When I write 3000000 (three million). It should appear 3.000.000

2. ONLY in the following fields of the socioeconomic:
a) Mi ingreso mensual es:
b) El monto de ingresos que generan los otros miembros de mi familia mensualmente:
c) Monto recibido (del gobierno) *This is displayed by a conditional question

---

@stacylorraineprendeville commented on [Wed Jul 03 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809#issuecomment-508040174)

@aprojas is this for reporting as well - I believe this should be 2 issues one for app / 1 for online
lets check in grooming

---

@Danman7 commented on [Thu Jul 04 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809#issuecomment-508379212)

@aprojas @stacylorraineprendeville We propose we use language as declaration of type of separator. `.` will be used when app is in English, `,` will be used when in Spanish. For which fields they apply to, we can use the field type of `number` which comes from the surveys. This way each field that has the possibility of large numbers will have separators so mentors don't do mistakes. If the field has less than 1000 of value, no separator would be visible anyway. This will not affect phone numbers, family members count and such.

If the above is working this means not implementation needed on backend.

---

@Danman7 commented on [Thu Jul 04 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809#issuecomment-508379876)

For Mentor App: https://github.com/FundacionParaguaya/MentorApp/issues/385

---

@stacylorraineprendeville commented on [Thu Jul 04 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809#issuecomment-508395514)

@javierpf does this need a seperate issue for the online?

---

@stacylorraineprendeville commented on [Sat Jul 06 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/809#issuecomment-508904332)

@javierpf please make the issue if you need one
@Danman7 I need the estimation on this!

**Comment by aprojas** [comment]
Please review one of the comments, it is incorrect 

1. Comma (,) should be for English
2. Period (.) should be for Spanish

@stacylorraineprendeville @javierpf

**Comment by aprojas** [comment]
where do I test this? @javierpf 
in the netlify link?

**Comment by javierpf** [comment]
yes @aprojas
