### ISSUE TITLE
Add support for sending lifemap pdf to the backend

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#511]

**Comment by gonzarodriguezt** [comment]
This is for the email endpoint right? @javierpf 

`/api/lifemap/send?familyEmail=:email`

**Comment by javierpf** [comment]
Looks like it is. Please to a look at [swagger](https://testing.backend.povertystoplight.org/swagger/index.html) doc. Also, you can confirm this with @loorely

**Comment by gonzarodriguezt** [comment]
I'm currently in progress with this, but i have a question, should i add a popup if the mail get to successfully being sent to the primary participant? Same with the other case, if an error is encountered @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt sure - we are missing a full ux on this feature

**Comment by gonzarodriguezt** [comment]
Test Template

Test Environment: Testing

Survey: Any

What to Test:
If receiving the lifemap email

How to Test:
When the survey is finished in the final screen, click on email and wait for the email
