### ISSUE TITLE
Indicators UI Fixes

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#512]
It should look like this: 

![Screen Shot 2019-07-08 at 10.54.31.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/ccae3165-ac7d-4b91-b1c4-2f1002145e83)

**Comment by gonzarodriguezt** [comment]
When i click on any part of this button it will display some options right? What options exactly?

![Screen Shot 2019-07-09 at 11.40.47.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/40a8013d-19f1-4c56-860e-9045375bac54)

**Comment by stacylorraineprendeville** [comment]
@gonzarodriguezt no options - it just shows another 10 - remove the liitle arrow - this is what has cause the confusion - correct?

**Comment by gonzarodriguezt** [comment]
Yes exactly, for the arrow i thought it was a select or something. Thank you @stacylorraineprendeville

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If the indicators section looks like the design shown in this ticket

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there
