### ISSUE TITLE
Scroll bar should not appear for short texts

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#518]
Environment: Web online, testing environment
Browser: Google Chrome

When clicking on the indicator definition, the definition of the indicator appears in a pop up box. 
When the text is long, the scroll bar should appear to scroll down inside of the box. 

BUT, the scroll down bar appears even though the text is not long enough. 

![indef.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d7785600-b5e9-41b0-ba92-10efb6fc909f)

![dfgdfg.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/9c1f1671-1f1f-4410-9c31-29d457c3a931)

**Comment by stacylorraineprendeville** [comment]
@aprojas we are missing the information on the environment. Can you review the bug template
For this we would need to know the browser version for instance - We cannot have bugs reported without this info.

**Comment by aprojas** [comment]
What do you mean environment? Even though it's a new feature and the team knows it's in testing?
@stacylorraineprendeville 
I updated the ticket

**Comment by stacylorraineprendeville** [comment]
Your environment in front end testing is thr browser version
can you check this with an alternative browser - find out if it is specific to one browser or not....
