### ISSUE TITLE
Add refresh token functionality

### ISSUE THREAD

**Issue by javierpf** [FundacionParaguaya/stoplight-web#527]
Currently, sessions are invalidated after ~10 hours. It causes the loss of all localStorage data, including drafts and session data.
Make use of the refresh token so we can automatically use it to get new session tokens and prevent unnecessary logouts.

**Comment by aprojas** [comment]
What did this mean? 
How can I test it?
@gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
Test Template @aprojas

Test Environment: Testing or Demo or Prod

Survey: Not aplicable

What to Test:
If the refresh token is working correctly

How to Test:
Kinda difficult to test as the functionality involves 10 hours in the description. But one way could be    login in and see if in the whole day the session don't expire. Any suggestions @javierpf?
