### ISSUE TITLE
Make Survey Screens Responsive

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#530]
Related #390 

We need the screens for the complete process of making a survey to be responsive.

**Comment by gonzarodriguezt** [comment]
Test Template @aprojas

Test Environment: Testing

Survey: Not aplicable

What to Test:
When on mobile version, the screens for taking a survey, all of them should look good

How to Test:
Change the view mode to mobile, instructions [here](https://superuser.com/questions/1214829/how-can-i-view-the-mobile-version-of-a-webpage-in-google-chrome-for-desktop)

**Comment by aprojas** [comment]
Not all screens have a good view in responsive. @gonzarodriguezt 

![responsivee.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/efab705d-011c-4fa0-89e2-3c2a2e4dee22)

![responsive.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/6e9a59a6-0446-42de-95a1-93a621df8459)

![responssive.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/998ca41c-cc6b-40e1-91c6-581c96d177b7)

**Comment by gonzarodriguezt** [comment]
Can you confirm those screens are in testing? @aprojas

**Comment by aprojas** [comment]
Just tested this and found two things to change: @gonzarodriguezt 

1. The surveys tab screen is mixing the the text in drafts section
![resp.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/c4c8fa50-4f76-4c5c-9107-53d68cf90451)

2. When in landscape/horizontal view, the stoplight indicators should be like the web, all the levels next to each other. 
![rspp.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5d653178-7d5b-49fe-aa11-9a8ae72f6c91)

**Comment by gonzarodriguezt** [comment]
Last changes done, the landscape/horizontal view could not be possible for this ticket, but we appreciate the attention to details :)

@aprojas
