### ISSUE TITLE
Fix bug in the UK Short Demo

### ISSUE THREAD

**Issue by JDelPuerto** [FundacionParaguaya/stoplight-web#534]
This new survey Uk Short Demo has no socioeconomic question, this case it's not contemplated  right now. It's expected that if the survey has no socioeconomic questions  then the stoplight indicators should be displayed.

**Comment by javierpf** [comment]
Changing the `bug` as this was not an expected case when developing the initial Economics section feature

**Comment by gonzarodriguezt** [comment]
In which environment and survey should i found this? @JDelPuerto

**Comment by JDelPuerto** [comment]
It will be on testing, but I will let you known when it's deployed @gonzarodriguezt

**Comment by JDelPuerto** [comment]
It's deployed on testing now @gonzarodriguezt  under the name of 'UK - SHORT DEMO'

**Comment by gonzarodriguezt** [comment]
Great thanks! @JDelPuerto

**Comment by aprojas** [comment]
This is not working in testing environment in the web. When I choose my location, all I see next is a blank screen with this direction: https://app.povertystoplight.org/lifemap/economics/0 

@gonzarodriguezt @JDelPuerto

**Comment by gonzarodriguezt** [comment]
I see, can you confirm if you did this test with the netlify url please? @aprojas

**Comment by aprojas** [comment]
Great! It works @gonzarodriguezt
