### ISSUE TITLE
Integrate Overview and Social Economics with Backend

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#540]
Integrate the Overview with the following querys, respectively:

```graphql
{
  blockOverview(organizations: [1]) {
    stoplightOverview {
      greens
      yellows
      reds
      skipped
    }
    priorities
  }
}
```

```
{
  economicOverview(organizations: [1]) {
    familiesCount
    peopleCount
  }
}
```

**Comment by gonzarodriguezt** [comment]
@aprojas 

*Test Environment:* [EnvName]
Options:
- Demo
- TestingNetlify

*Survey*: Not aplicable

*What to Test*:
If socio economics and overview sections displays real data and they work fine

*How to Test*:
Go to `/dashboard/` as a demo user, it should be there

**Comment by aprojas** [comment]
This was not showing real data from testing, was it? @gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
It should, besides from the bug you caught some days ago on the bars:

<img width="982" alt="Screen Shot 2019-07-22 at 09 47 45" src="https://user-images.githubusercontent.com/13141462/61637564-c6e3c100-ac65-11e9-8fe2-a42298be21d5.png">
