### ISSUE TITLE
Lifemap does not fit in different print size pages

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#544]
Environment: all of them

When I finish the lifemap and priorities, and click on "Print", the whole lifemap does not fit properly in most of the size pages. 

1. Print version for A4 size
![print A4.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ea63bd16-b938-4c22-b8f6-13ef41bc5df0)

2. Print version for Letter size
![Print Letter.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/541cdc0c-9ff1-4050-9778-c830cedefd32)

3. Print version for Legal size 
![Print Legal.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/64d6f00a-9558-4fcb-b354-441a4130df6f)

4. Print version for Statement size 
![Print Statement.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/4a1d8c57-7938-4c21-9408-b87fb055fd84)

5. Print version for Executive size 
![Print Executive.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/911b4d44-720b-47ba-bd64-8119633f7d88)

**Comment by stacylorraineprendeville** [comment]
@aprojas can clients not select the fit to page option?
Every printer has different margins and paddings.............or is this something else @javierpf

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you provide some further information
Can this issue not be solved simply by selecting "Fit to Page" options?

**Comment by aprojas** [comment]
Yes! This can be solved by selecting "Fit to page". It's just strange since before it was fitted normally when just clicking on "print", with no need of going to the "fit to page" option. 
I guess it's not necessary to solve. @stacylorraineprendeville
