### ISSUE TITLE
Numbers in pie and bar chart not linked in Overview

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#553]
In the Overview chart, the numbers that are shown in the pie chart are not the same as the ones shown in the bar chart. 

![qqqqqwe.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ff8e05fc-b476-4c25-99f6-901d421399a0)

**Comment by gonzarodriguezt** [comment]
This is addressed on #557 as well! @aprojas Thank you
