### ISSUE TITLE
Dimension and indicator are not linked in Dimension bar chart

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#554]
The dimension and the belonging indicator is not showing the same number, I think it is not linked. 

See the following screenshots:

![qwer.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/df3a991b-e7a1-4a6d-810e-0df4f3bd916a)

![qwert.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/badcf02a-cf83-49cc-8317-44882090acd1)

**Comment by javierpf** [comment]
We've realized there is a bug in the data retrieval from the backend side. Probably will be solved after that bug gets fixed
