### ISSUE TITLE
Incorrect month in Operations chart

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#555]
It should be

MAY - JUN - JUL - AGO

It says:

MAY - ENE - JUL - AGO

![qqwqwwqeqw.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/429d606f-5161-430a-b452-8731e6b1901a)

**Comment by gonzarodriguezt** [comment]
Related to #494 

Should be fixed when merging the above ticket @aprojas

**Comment by gonzarodriguezt** [comment]
Now that #494 this is fixed @aprojas
