### ISSUE TITLE
Circle of Tooltip is cut in half 

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#558]
The design of the last tooltip circle is cut in half. It should have been like the following screenshot:

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/8fbad639-5b37-46fe-acfb-e90bede67477)

**Comment by gonzarodriguezt** [comment]
This is also addressed in #557, we can follow it there @aprojas
