### ISSUE TITLE
Overview and Socioeconomics not as design

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#561]
The overview and socioeconomics part of the dashboard screen is not the same as the one designed. There is a lot of white middle space.

Expectation:
![sssda.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ba8e4163-48bd-4553-a87b-56c9dcdf7964)

Reality:
![dashbaord.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/812de640-2610-4dfe-8235-cedf2229bf8c)

**Comment by gonzarodriguezt** [comment]
This is addressed in #557, should we close this and follow this bug there?
