### ISSUE TITLE
Move priority icons closer to the pie chart and remove 0 icons

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#585]
In the dashboard screen:

1. The priority and achievement icons should be closer to the pie chart
2. The icons for "0" priorities and achievements should not be there, it is irrelevant.

Follow this design: 
![Screen Shot 2019-07-26 at 11.26.17.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/9d56651b-f2f9-4a40-b1e8-fc0cf55742b2)

**Comment by aprojas** [comment]
Hi @gonzarodriguezt this does not look like the design. 

![pop.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/7d98f7e1-5e5d-4be3-9eca-64b3ec26d743)

**Comment by gonzarodriguezt** [comment]
I don't know why i was sure that i already changed it! Thanks @aprojas
