### ISSUE TITLE
Incorrect number of families

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#589]
I logged in the testing environment
with user: nelixiademo
which only has 1 survey and has a few surveys taken this week. 

However, in the main screen where the drafts are found, I found a large number:

![familiess.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ba21e5b8-d9fe-4ee3-a043-f919f2918a29)

**Comment by javierpf** [comment]
@loorely @diegotorrespy probably backend-related. Any ideas?

**Comment by stacylorraineprendeville** [comment]
@diegotorrespy This is from the previous sprint - where are we with this issue?

**Comment by aprojas** [comment]
It's not happening anymore. @diegotorrespy 

I will close it!
