### ISSUE TITLE
New surveys not showing in Activity Feed

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#590]
Environment: Testing netlify
User: nelixiademo
Type of user: mentor

Problem:
I took a new survey in the testing netlify link from the nelixiademo account, finished then, and then went to the dashboard (by changing the URL)
In the dashboard, I saw that the count of socioeconomic went up from 11 to 12. 
But the Activity Feed was empty.

![qqqqwe.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d8b30381-92cc-4684-97ba-81f1136cff8b)

![uil.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ce0e63a0-5b9c-4f2f-91b7-5e5be2357336)

**Comment by gonzarodriguezt** [comment]
I think this is because mentor role users cannot see the activity feed, can you confirm? @loorely

**Comment by aprojas** [comment]
Hmm.. don't understand. Then there won't be a dashboard for mentor users? Or only a section of a dashboard? @stacylorraineprendeville

**Comment by loorely** [comment]
@aprojas @stacylorraineprendeville This is a backend for this issue. I'll do the changes accordingly
