### ISSUE TITLE
Review date on the Operations chart

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#591]
When you hover over the dot, it shows you a date and a number of surveys, it makes you believe that up to that date, an X amount of surveys were taken. But it actually shows you the amount of surveys of that month. 

See the following screenshot:
I filtered by the Organization Nelixia, and I know that many surveys were taken this week within the org Nelixia. When I hover over the dot, it says July 1 and 6 surveys, but I know these surveys were taken even after July 1. 
![surveysss.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ce11838e-c086-45ba-bafe-aee1eb15613a)

Please talk to @stacylorraineprendeville about this

**Comment by gonzarodriguezt** [comment]
@diegotorrespy Do you have some insights on why this is the current behaviour?

**Comment by gonzarodriguezt** [comment]
How can we move forward with this? @aprojas @diegotorrespy

**Comment by diegotorrespy** [comment]
@gonzarodriguezt @aprojas 

For as I know this issue was solved showing only the month name and the year without the number, for example `July 2019` instead of  `July 1, 2019`  in order to not confuse the dates.

**Comment by aprojas** [comment]
You are completely right @diegotorrespy 
I'll close it @gonzarodriguezt
