### ISSUE TITLE
Design Amendments to the resume draft

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#592]
- Rename from Choose a survey to “Welcome Demo”

- Add more height in the overview and surveys blocks (30 pixels?)
- Scrollbar should be visible be default when required.

- Families Search box to be on the same line (right aligned) as the title Drafts
- Text in family search box should be Search Families not Search Family

- Lets change the text within the modal
Title to: Are you sure you want to exit?
Then..Your Life Map is not complete
It will be saved as a draft

- Can the whole table row be clickable in the Drafts area - rather than just the small arrow.

**Comment by stacylorraineprendeville** [comment]
@aprojas why assign to me? This is all completed - Correct? @javierpf

**Comment by javierpf** [comment]
It is @stacylorraineprendeville
