### ISSUE TITLE
Handle all roles and their items

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#605]
This is for handling all roles and their items

**Comment by stacylorraineprendeville** [comment]
? where?

**Comment by gonzarodriguezt** [comment]
Sorry! In the items of the header, did it in a rush @stacylorraineprendeville

**Comment by gonzarodriguezt** [comment]
Test Template @aprojas 

Test Environment: Testing/Demo/Prod 

Survey Not aplicable

What to Test:
The items in the header for each role should match the items in the header on PSP for each respective role.

How to Test:
Login which a specific role and compare the items in the header between PSP and Stoplight Web
