### ISSUE TITLE
Change order of indicators - Dashboard

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#620]
The order of the indicators should be alphabetical. 
Not in a random order.
This should be implemented in ALL dashboards, of all users. 

![tgbjnfhb.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/2060ab10-b5fc-4239-873e-220460656721)

**Comment by javierpf** [comment]
@stacylorraineprendeville @aprojas Since displaying indicators in the same they appear when taking a survey is not a trivial task, we'll sort indicators (and also dimensions) alphabetically.

**Comment by aprojas** [comment]
Can we implement the dimensions in a certain specific order?
1. Income and Employment
2. Health and Environment
3. Housing and Infrastructure
4. Education and Culture
5. Organization and Participation
6. Interiority and Motivation

They are always set like this in every survey, and methodologically, we use them with this order always. 

@javierpf @stacylorraineprendeville

**Comment by aprojas** [comment]
Ready! @javierpf
