### ISSUE TITLE
Solving the re-direct flash

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#622]
Issue to solve the re-direct flash when loading the platform

**Comment by gonzarodriguezt** [comment]
Test Template @aprojas 

Test Environment: Testing

Survey: Not aplicable
Options: Not aplicable

What to Test:
When logging on `https://testing.povertystoplight.org/login.html` it should redirect automatically to `https://app.povertystoplight.org/surveys`. Without any flashes.

The same should be working with all elements on the header, no flashes, just direct to the new platform.

How to Test:
Login in and clicking to items in the header of the old platform, looking and comparing to how was redirecting in `demo.povertystoplight.org` may be useful
