### ISSUE TITLE
Add text before mentor name

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#625]
### Problem

In the design we referred to the mentor in the activity feed as "mentor name" which looked fine in the design template - Now we see in the activity feed the results and the two names together are confusing
![Screen Shot 2019-08-05 at 13.44.05.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/00b157f2-4c3d-4cf8-9214-2cd2bdcebbb4)

### Solution
Add the text "Facilitator:" before the name of the facilitator.

e.g. Facilitator: Leanne Rogers

**Comment by gonzarodriguezt** [comment]
The facilitator's name after the text, should be capitalized? @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
better to - before we get another complaint ;) @gonzarodriguezt
