### ISSUE TITLE
Color Adjustment in Charts

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#626]
## Problem
The current color of the months and figures grey  in the chart information is very light and therefore difficult to read.

![Screen Shot 2019-08-05 at 13.46.42.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/333a490b-2164-4cb9-ae83-4a444bf496df)

## Solution
Change this colour to #909090

**Comment by aprojas** [comment]
I do not see this in testing @gonzarodriguezt @javierpf 
From the demo/demo account
