### ISSUE TITLE
The new stoplights screen

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#627]
## Problem

The current stoplights screen does not maintain the format of the new lifemap

![Screen Shot 2019-08-05 at 15.30.29.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c3215cb6-abe0-46ad-8319-ccd77029d761)

## Solution

Create the new stoplights screen which retains the new print format and new design

Main Page
![Screen Shot 2019-08-05 at 15.32.08.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/ec6acc52-2a93-40fd-9642-8f93a1a275eb)
![Screen Shot 2019-08-05 at 15.32.44.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/c17f5214-a60d-4f31-8d74-97f6a6a8ba1a)

Visible at:https://projects.invisionapp.com/d/main?origin=v7#/console/18040017/375469908/preview
https://projects.invisionapp.com/d/main?origin=v7#/console/18040017/375469906/preview

## Requirement
This will NOT be merged to production until we have improved the entire section - please be aware of this in developing

**Comment by gonzarodriguezt** [comment]
Help with estimation please! @javierpf
