### ISSUE TITLE
Add delete option for Drafts

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#629]
### Problem
---
If a mentor user has several drafts, and might not continue with them to finish a survey. They will have several drafts in their account without any use for them. 

### Solution
---
Implement a button or some type of feature which gives the mentor/facilitator user to delete drafts if they will not need them anymore.  
Use of this button must be followed by a modal window asking for confirmation as is standard throughtout the site.

![Screen Shot 2019-08-15 at 08.59.58.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/114fea7c-0741-45c4-bdcb-c9451b087a8f)

![Screen Shot 2019-08-15 at 09.30.36.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/fe148ba9-51e6-4520-8439-cd1742af2c98)

**Comment by stacylorraineprendeville** [comment]
Just thinking about this
We can only add this to the list.....
I am not keen on adding a new style of delete icon now we know that we will not finish all the platform in the new design....So we will use the current icon.
( @javierpf  Do we have this icon anywhere on the server in vector format??? If not I will need to recreate it to get the right colour shade)
![Screen Shot 2019-08-14 at 15.48.35.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/72edddf0-e1d6-4089-b463-229c30eb92ae)

**Comment by javierpf** [comment]
@stacylorraineprendeville yes, we have that icon available from the [material-icons](https://material.io/resources/icons/?icon=delete_forever&style=baseline) project.

**Comment by stacylorraineprendeville** [comment]
Perfect @javierpf I wanted to confirm a few more things about Mentors and resume Drafts.

Drafts are only available to the mentor that creates them.
Correct?
What about the facilitator admin account that has access to all families - They still only see the drafts that they created - correct?
A draft once created does not create a family until the draft is completed? - Correct?

**Comment by stacylorraineprendeville** [comment]
![Screen Shot 2019-08-15 at 09.27.17.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/4bc22747-50b0-4e67-bf3f-604176a30ea0)
We can just use our standard modal that we created for the resume draft feature - I would stay away from making text changes as we need not to increment time..

@javierpf

**Comment by aprojas** [comment]
Some thoughts..
1. Facilitators and Facilitator Admins will have the option to delete drafts, right?
2. The modal will always appear when clicking on the delete icon, doesn't matter if they completed more than the First and last name, right?
3. I think that delete icon is great

@stacylorraineprendeville

**Comment by javierpf** [comment]
@stacylorraineprendeville Drafts are only visible by the mentor that created them. Families are not created based on drafts, the family gets created when a survey is successfully completed.
