### ISSUE TITLE
Order of dimensions in Dashboard

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#630]
Environment: All of them
Section: Dimension list of Dashboard
Action required: Change the order of the dimensions

This order is preferred by Methodology:
1. Income and Employment
2. Health and Environment
3. Housing and Infrastructure
4. Education and Culture
5. Organization and Participation
6. Interiority and Motivation

They are always set like this in every survey, and methodologically, we use them with this order always.

**Comment by stacylorraineprendeville** [comment]
@aprojas Kathi has told me the exact opposite - that the order is not fixed - this came out of a conversation we had about changing the format of the poverty stioplight in future and not adding so many questions in the beginning.
Lots of contradictory information
