### ISSUE TITLE
Capitalisation of names

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#635]
Environment: Demo and Production

Problem:
The name of Hubs and Orgs sometimes has more than one upper case letter, and it is not properly displayed in the Dashboard after the word "Welcome [name]".

Solution:
It should be displayed exactly as the name is created. 

See screenshot: In the upper corner it says "Transmit Enterprise" but in the dashboard it shows "Transmit enterprise"

![Screenshot 2019-08-07 07.53.14.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/6726f33f-fd9c-4fb8-b7a5-3defaca222fc)

**Comment by aprojas** [comment]
This works in the dashboard. But if I'm a mentor, it should also show in the survey tab. For example "Welcome Demo User". 
@gonzarodriguezt 
![lolo.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/20d5e4dc-de66-4a5b-b3b5-ab1854114df2)

**Comment by gonzarodriguezt** [comment]
I'll work on that! @aprojas 

Thanks
