### ISSUE TITLE
Handle new role in header

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#642]
The header should be able to show the correct items for `ROLE_SURVEY_USER_ADMIN`.

**Comment by gonzarodriguezt** [comment]
@stacylorraineprendeville Quick question about this role in the PSP platform, when login on PSP, it should redirect to `/dashboard` or `/surveys`?

**Comment by stacylorraineprendeville** [comment]
When a mentor logs in it goes to the surveys page
When a hub or org logs in - it should go to the dashbaord.

If we want we can remove the surveys page for the mentor and just have the mentors home page as the surveys screen with resume draft?
@gonzarodriguezt

**Comment by gonzarodriguezt** [comment]
I don't know if i got that correctly, the surveys page is in PSP, and the surveys screen in stoplight-web?
