### ISSUE TITLE
Ensure that the print version of the life map is identical throughout the site

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#646]

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you check this . When you go to an existing family and print of the life map - is it the new style that is utulised?

**Comment by aprojas** [comment]
When I go to an existing family and print the lifemap, it has the old style still 
@stacylorraineprendeville 

![oldprint](https://user-images.githubusercontent.com/44477708/62778778-4f909880-ba7f-11e9-8c0d-42b0fce37af7.PNG)
