### ISSUE TITLE
Removing and Resolving the Re-Direct on the Mentor Account

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#660]
## Problem
Since last year a redirect was in place for the mentor user to direct to the surveys page on login.
The reasons seem fairly unknown however recently the new dashboard was pushed incorrectly removing this redirect and giving the organisation view - This view was NOT designed for the mentor! We recevied immediately a client complaint about having made "changes".

## Solution
Correctly design and implement a solution
1. Dashboard - Remove the Organisations filters on the mentor dashboard.
2. Dashboard - Remove the dimensions visualisation on the mentor dashboard. - These are not relevant to all clients
3. Dashboard - Refer to the drafts on the dashboard? Add the survey? (Later)
4. Dashboard - Change operations title to "Your Progress"
4. Surveys Page - Use Title Surveys
5. Surveys Page - Change the overview block potentially to number of drafts?? The overview block would be repeated if not amended. (can be seperate issue later)
6. Remove the Re-direct

**Comment by aprojas** [comment]
About this comment:

5. Surveys Page - Change the overview block potentially to number of drafts?? The overview block would be repeated if not amended. (can be seperate issue later)

Did Stacy refer this to changing the title "Overview" to "Number of drafts"?

@gonzarodriguezt @javierpf

**Comment by gonzarodriguezt** [comment]
Not sure @aprojas 

I left it as an `Overview` of the surveys page, what do you think? @javierpf
