### ISSUE TITLE
Administrative Tasks associated with moving to maps per org

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#662]
## Problem
Maps will move to a per organisation structure rather than per survey - to counteract heavy download times

## Solution
Clients most notably Emprender will need to provide information regarding maps per org.
Other clients with a smaller number of maps will need the information inputted in the platform to be available to the app

1. Create list of all clients using Offline Maps with full details of individually downloaded areas.
2. TBD

**Comment by stacylorraineprendeville** [comment]
@javierpf @diegotorrespy Admin user I presume will be allowed to add maps per organisation.
@loorely the PS TEAM USER can also be given this right?

**Comment by aprojas** [comment]
The partners who have offline maps are:

1. Emprender
2. Nelixia
3. Geco
4. Chortitzer

@stacylorraineprendeville

**Comment by JDelPuerto** [comment]
Two list of offline maps per organization will be necessary one for Production and another one for D emo. Also @stacylorraineprendeville  if a partner wants another organization to have a certain offline map will have to notify us so we can add it, as they do now, to give an admin the chance of adding an offline map to another organization it's a separate feature.

**Comment by stacylorraineprendeville** [comment]
@JDelPuerto As I understand we will add them an d you are talking about the HUB or ORG user being able to change this being a new feature - Correct?

**Comment by stacylorraineprendeville** [comment]
1. Emprender has the following Organisations
![Screen Shot 2019-08-30 at 14.43.25.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/74302306-7ca7-43fe-95dc-8087dceb8b95)
@aprojas Can you find out which maps pertain to which org

2. Nelixia does not have multiple ORGS - Here we can complete the back end without need to ask the client.

3. GECO - As above

4. Chortitzer only has one map - Currently I cannot see this Hub on the platform under admin in the dashboard @aprojas is this part of another bug?
In regards to maps - as above

**Comment by stacylorraineprendeville** [comment]
---waiting on above
Replicas (JuanFer) to provide information regarding which maps for which org before this feature can be moved to production
