### ISSUE TITLE
Change text in TC & PP buttons

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#682]
Environment: All
Surveys: All
Screens: Terms and Conditions ; Privacy Policy
Language: Spanish

Problem
---
Now, the buttons to accept the TC and PP are different in Spanish in both the mobile app and web. 

Solution
---
Change the names of the buttons in the WEB to the following:

Change de acuerdo: Acepto
Change Desacuerdo: No acepto 

![acee.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/0d636890-db2e-48cb-8e94-6c754c2d5053)

**Comment by stacylorraineprendeville** [comment]
@aprojas This would need a seperate ticket for the Mobile

**Comment by aprojas** [comment]
It's already correct in the Stoplight Mobile. 
@stacylorraineprendeville
