### ISSUE TITLE
Styling on Dashboard when nothing is found

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#691]
We need to remove the padding on Activity Feed and get back the title missing

![Screen Shot 2019-08-30 at 14.03.22.png](https://images.zenhubusercontent.com/5cab5d8c92ef213fe49ffb42/3cd49b00-8534-44d8-8100-6699d1164a03)

**Comment by aprojas** [comment]
The only section that still shows data is "Latest Activity"
Is it supposed to be like this anyways?
@javierpf
