### ISSUE TITLE
Allow users to take the lifemap survey from platform.povertystoplight (integration)

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-web#72]
Integrate lifemap survey on stoplight-web (app.povertystoplight.org) within fp-psp-frontend (platform.povertystoplight.org) so that they can click a link from platform.povertystoplight and take the survey 

while ensuring that authentication is correct and the user is given the correct surveys.

**Comment by gigerbytes** [comment]
@pA1nD  pls review.

**Comment by pA1nD** [comment]
The back-buttons are still sending you to testing.

**Comment by gigerbytes** [comment]
This should await deploy date as it will affect the prod platform.
