### ISSUE TITLE
Month NOVEMBER doesn't show in Operations chart

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#721]
Environment: Platform
User: Root Admin

In the dashboard, in the operations chart, the month NOV is not shown

![adsfdsdgsg.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/103f6e39-37c4-49d1-a5ff-552adf595267)

**Comment by loorely** [comment]
@aprojas looks like it is working: 

![image](https://user-images.githubusercontent.com/740232/66530499-65055b80-eade-11e9-999e-23225b0f7dc8.png)


Can you provide the user login and filters that is showing the error?

**Comment by aprojas** [comment]
Sorry, it doesn't work with the ENGLISH language.

@loorely

**Comment by aprojas** [comment]
This is how I see it in Root Admin when choosing ENG language. @loorely 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/815d8b4f-37bc-42f9-87db-fd02885def49)

**Comment by aprojas** [comment]
That's weird.. now I see it. @loorely
