### ISSUE TITLE
Filter loses when searching with pagination

### ISSUE THREAD

**Issue by gonzarodriguezt** [FundacionParaguaya/stoplight-web#723]
@gonzarodriguezt commented on [Tue Oct 01 2019](https://github.com/FundacionParaguaya/fp-psp-frontend/issues/461)

Whit the introduction of pagination in #443, filter's state is loss after the first search, it'll be better to keep it during the whole interaction.

**Comment by aprojas** [comment]
This is not working still. If I filter the pagination by org or family name, the input of the field is erased after I click on search. 

@loorely

**Comment by loorely** [comment]
@aprojas not sure about the bug here. Can we do a demo testing?

**Comment by aprojas** [comment]
In the Organization select list, add the option "All" in English and "Todos" in Spanish. 

In the text field of search by family name, it should be the same functionality as the one in the Users tab. 

@loorely

**Comment by loorely** [comment]
## Solution 

For Organization Combobox allow " All Orgaization" option and keep the filter selected all the time.
