### ISSUE TITLE
Reports button not showing for ps team

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#728]
Environment: all of them

Problem
---
When logging in with a psteam user, I cannot see the Reports tab in the header. However, if I click on one of the buttons of the old psp, that's when the Reports tab appears. 

![Annotation 2019-10-08 102724.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/7c954592-ecd1-44e9-9743-bdcb8e470fa6)

**Comment by loorely** [comment]
It is working on stoplight-web. I test the testing env: 

![image](https://user-images.githubusercontent.com/740232/66526215-3ed7bf80-eace-11e9-9991-90047786f1bb.png)

@aprojas can you check that again?

**Comment by aprojas** [comment]
Yes! It is working in testing. 
Ready for the next release then @loorely
