### ISSUE TITLE
Family Members Gender and Age pages do not correctly add the family member name.

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#76]
When I go to the family members page  - I add a second family member - Named Juanfer.
![Screen Shot 2019-01-23 at 12.26.14.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/e504dac5-c704-4865-9c02-b3ef5ba069b3)

The next screen should then ask me for the gender of "Juanfer" but it does not - it asks for "Stacy F"?
![Screen Shot 2019-01-23 at 12.26.21.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/08606588-6dcf-4a72-b409-9e464bd58c3f)

Simalarly on the birth dates page - The title given is the birth date of the primary participant - But this should be the name "JuanFer" whose birthdate we are asking for
![Screen Shot 2019-01-23 at 12.28.25.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/4afd7c1d-8d20-496e-a074-56e341846116)

If I use the go back button when I only have one family member - then it incorrectly leads me to the birthdates page (this should only be visible if I have selected additional family members) I presume rectifying the above will resolve this.

**Comment by gigerbytes** [comment]
@pA1nD Pls review.

**Comment by pA1nD** [comment]
Works.
