### ISSUE TITLE
Create Process to Ensure changes to the App regarding surveys are also changed on the Web App

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#81]

**Comment by pA1nD** [comment]
### Problem

Changes in the App and in the Web App should be deployed at the same time.
The App deployments are timed, the web app deployments can be more flexible.

### Solutions

Considering, that both features should be deployed at the same time, the app can be considered depending on the web app.

Two possible ways would be (to discussed with the team):

(1) Add two issues for everything that has to be changed in the frontend and to add a dependency between them. They could also be linked via an epic.

(2) Add one issue with both descriptions for app and web.

**Comment by pA1nD** [comment]
Recommendation: Features should be always added as epic.
