### ISSUE TITLE
Click on upload files to preview file

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#820]
When the user uploads a file in the section to add pictures, they will want to preview their file if they uploaded it correctly. The file has to seem hyperlinked. 
This feature has to simulate what happens also in the Gmail.

Steps:
1. Upload a file
2. See the uploaded files in a list below
3. Click on one of the files
4. The file should open in another tab as a PDF or JPG or something else.

**Comment by aprojas** [comment]
Not all files have the option to preview it!

![Annotation 2020-03-09 140425.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/078e63a2-87fb-4b9e-951e-f00b28eb8803)

@JDelPuerto

**Comment by JDelPuerto** [comment]
Once you leave the page, the images previously uploaded can no longer be previewed @aprojas. I had to make the decision to prevent errors in case that the user reloads the browser.

**Comment by JDelPuerto** [comment]
Ready for testing @aprojas
