### ISSUE TITLE
Signature is distorted when going back

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#828]
Env: in Testing

When I sign in the web and move forward, but then go back to review my signature, the signature is distorted:

Original:
![Annotation 2020-02-14 092520.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/bbb03b37-4f5b-4bfe-87ab-afe7adfce8d9)

Distorted:
![Annotation 2020-02-14 092548.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/cac4dedc-89a7-4974-8507-c20a34591ef4)

**Comment by JDelPuerto** [comment]
You should try this on several different devices @aprojas

**Comment by aprojas** [comment]
You mean browsers? @JDelPuerto

**Comment by JDelPuerto** [comment]
Yes!
