### ISSUE TITLE
Take out link "View Life Map in detail" in family profile if skippedStoplight is true

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#842]
In the Family Profile, if the family has not taken their Stoplight yet, the link to "View your Life Map in detail" shouldn't appear. Or else it would take you to another page with 0 information

**Comment by JDelPuerto** [comment]
This is already done in this [PR](https://github.com/FundacionParaguaya/stoplight-web/pull/853)
