### ISSUE TITLE
Wrong number of lifemap taken in family profile

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/stoplight-web#874]
After 2 lifemap retake it shows the wrong number in family profile

![image.png](https://images.zenhubusercontent.com/5907a75d51aa2c30577cf78c/2f9bb1ae-aa75-44f2-a60e-95b11f58f08d)

**Comment by JDelPuerto** [comment]
@loorely  This bug appears to be already solved in this PR https://github.com/FundacionParaguaya/stoplight-web/pull/871

Can you test it there?
