### ISSUE TITLE
Hide/show retake button according to hub configuration

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/stoplight-web#878]
1. Modify login request ``/api/v1/users/validate``  to get ApplicationDTO json and support_retake param. Save this information in local storage as part of user information. 
2. Use support_retake param to hide/show the retake button in the family profile view.

**Comment by JDelPuerto** [comment]
This is ready for testing, from now on  the retake button will appear  to "hub" in testing. @aprojas
