### ISSUE TITLE
Implement Report Frontend

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/stoplight-web#9]
#### Organization
As an organization, I should be able to:
- Filter the families snapshots
- by Survey
- by Snapshot Indicators
- by SocioEconomic Indicators
- by Time Period

I should additionally be able to download a csv file of the filtered information

#### Hub
As a Hub, I should be able to do the things that an organization can. Additionally, I should be able to filter by organization or select a subset of multiple organizations.

### Acceptance Criteria
GIVEN the Report Form Page

WHEN wanting to download a subset of snapshots according to filtered parameters as an Organization User
- [ ] THEN it provides an interface where I can set my filters
- [ ] AND it provides a Time Filter with the options
    - [ ] All Time
    - [ ] Past 6 Months
    - [ ] Custom Date Range
- [ ] AND it has a multi-select dropdown to pick one or more surveys
- [ ] AND it has a section to filter by Socio Economic Answers
    * WHERE each Socio Economic question is filterable
    - [ ] With all selected being the default
    - [ ] Number/Text Fields have a `From` and `To` range
    - [ ] Dropdown Fields are multiselect and are prepopulated with the possible answers
- [ ] AND it has a section to filter by Stoplight Indicators
    * WHERE Each Stoplight Indicator is filterable
    - [ ] WITH All selected being the default
    - [ ] AND I can select one or all Stoplight Colors

WHEN I'm finished filling in my filters
- [ ] THEN there is a `Preview Results` button to allow me to see the results of my filter
- [ ] AND there is a `Download CSV` which downloads the results when I click it

WHEN Wanting do download a subset of snapshots according to filtered parameters as a HUB user
- [ ] THEN it provides the same interface as that of the Organization user
- [ ] AND it has a multi-select dropdown to pick one or more organizations

**Comment by stacylorraineprendeville** [comment]
@gigerbytes Is it possible to remove the preview results button and simply be updating this list visually on the page with each filter?

**Comment by pA1nD** [comment]
We should wait for a design before implementing this.
