### ISSUE TITLE
Change final flow when finishing survey

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#903]
This will be the new flow of the survey:

1. When the user arrives to the OVERVIEW where they can create priorities and achievements, the button will still say CONTINUE.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f68e0190-2936-4050-88ca-9ffed244f849)

2. After they click on CONTINUE, the next screen (a new one) will say "Congratulations! You have finished your survey. Choose Finish to send your survey." The button will change to "FINISH".

3. When the user clicks on FINISH, the survey will be sent to the backend. AND it will take them to the screen of sending the Life Map.

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1758d8da-0950-4a84-8807-a0e02eb98108)

- Then the user chooses to download or send the Life Map, this will help for them to receive the life map generated in the backend.

4. Then they click on OK and they will be redirected to the main page, or if they exit the whole browser, nothing will happen.

**Observations:**
- What happens when they have add pictures or signature? Should the "Finish" button to send the results to the platform be automatically in the last survey screen? Like the signature or pictures one if they have it?
- Diego spoke of the possibility to have the "Review your answers" screen before sending it to the backend, and before the Send Lifemap options screen. And when they review their answers, then they click on Finish.

**CONCLUSIONS:**
- The first version will only include a new screen after the final survey screen (like overview, pictures or signature) be the "Title: Congratulations! Subtitle: You have finished your survey. Choose Finish to send your survey."

- The second version will be the complete REVIEW YOUR ANSWERS

# NEW TEXTS

## Finish Screen

**SPANISH**
Title: `¡Gracias!`
Subtitle: `
¡Felicidades! 
Ya respondiste todas las preguntas.
¡No te olvides de finalizar tu encuesta!
`
Button: `Finalizar`

**ENGLISH**
Title: `Thank you!`
Subtitle: `
Congratulations!
You answered all of the questions.
Don’t forget to finish your survey!
`
Button: `Finish`

**PORTUGUESE**
Title: `Obrigado!`
Subtitle: `
Parabéns! 
Você respondeu a todas as perguntas.
Não se esqueça de terminar a sua pesquisa!
`
Button: `Fim`

## Send Life Map screen

**SPANISH**
Title: `Envía tu Mapa de Vida`
Subtitle: `
¡Listo! Ya terminaste tu encuesta. 
Si quieres recibir o descargar tu Mapa de Vida, selecciona una de las siguientes opciones:
`
Button: `Ok`

**ENGLISH**
Title: `Send your Life Map`
Subtitle: `
Great! You finished your survey. 
If you wish to receive or download your Life Map, click on one of the following options:
`
Button: `Ok`

**PORTUGUESE**
Title: `Envie o seu Mapa de Vida`
Subtitle: `
Pronto! Já terminou a sua pesquisa. 
Se você gostaria de receber ou baixar seu Mapa de Vida, por favor selecione uma das opções abaixo:
`
Button: `Ok`

## Email modal

**SPANISH**
Title: ¡Listo!
Subtitle: Tu Mapa de Vida ha sido enviado exitosamente vía email.
Button: Ok

**ENGLISH**
Title: Great!
Subtitle: Your Life Map has been successfully sent via email.
Button: Ok

**PORTUGUESE**
Title: Pronto!
Subtitle: Seu Mapa de Vida foi enviado exitosamente via email.
Button: Ok

**Comment by aprojas** [comment]
Comment:
When I click on the button "Return to Home Page", the drafts don't appear anymore and it shows a continuous loading circle. @JDelPuerto 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/ed3614b7-f9de-42ae-840a-a9fc315c9b29)

**Comment by JDelPuerto** [comment]
Can you  post a screenshot of the loading circle @aprojas ? I think  the cause of the bug  was testing being down for a few minutes.

**Comment by aprojas** [comment]
Here it is: @JDelPuerto 

![image.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/1b1c57e6-29a6-464a-a955-9d8b43a50e9d)
