### ISSUE TITLE
404 Page for Stoplight Web

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/stoplight-web#966]
## Problem
We need to control the user role in order to show or hide some specific path in stoplight web. 

Example:
Survey User shouldn't be allowed to go to /organizations/ path

## Solution
- A new function in app.js to verify the access of views depending of the roles in roles-utils.js 

/priorities (from Family Profile, with modal)
- Facilitators
- Admin Facilitators

/detail/familyID
- Denied to ps_team_user and Surveyor

**Comment by aprojas** [comment]
The PS_TEAM_USER should have access to the organizations list when they click on the arrow of the Hub

@JDelPuerto
